/* The Entertainment room's list — what Ric has watched and what is queued up.

   This file is the committed truth. The page renders it, and an edit made on the
   page (adding a title, moving one from the queue to watched) is layered on top of
   it at read time rather than rewritten into it — same shape as the climbing
   section, where the committed history stands on its own and the service only ever
   adds to it. Two things can supply that layer:

     · the Worker's /movies endpoint, when it is deployed — public to read,
       Ric's token to write, so an edit follows him between phone and laptop and
       visitors see it too;
     · this browser's localStorage, when the Worker is not reachable — which is
       every edit made before the Worker ships, and any made while it is down.

   Either way the edits stay OUT of this file until someone commits them. The page's
   owner panel has an Export button that prints a replacement for this file with the
   pending edits folded in; paste it over this one and the layer empties itself.

   Fields:
     id      slug, and the key both storage layers use — do not renumber or reuse
     title   as it should read on the page
     status  "watched" | "watchlist"
     count   how many of a franchise Ric counted ("Saw(1-10)" → 10)
     series  true where he wrote "(all)" and a number would be a guess
     where   how he'd get at it: a service name, or "Buy"
     pick    he starred it — top of the queue
     note    anything the raw list said that the fields above cannot hold

   Titles are his list, lightly corrected for spelling and casing. Where a title was
   ambiguous it was left as typed rather than guessed at — see README. */
window.ENTERTAINMENT_DATA = [
  { id: "2-guns", title: "2 Guns", status: "watched" },
  { id: "the-equalizer", title: "The Equalizer", status: "watched" },
  { id: "the-accountant", title: "The Accountant", status: "watched" },
  { id: "american-gangster", title: "American Gangster", status: "watched" },
  { id: "keep-watching", title: "Keep Watching", status: "watched" },
  { id: "the-belko-experiment", title: "The Belko Experiment", status: "watched" },
  { id: "the-last-stand", title: "The Last Stand", status: "watched" },
  { id: "patriots-day", title: "Patriots Day", status: "watched" },
  { id: "sahara", title: "Sahara", status: "watched" },
  { id: "mud", title: "Mud", status: "watched" },
  { id: "white-boy-rick", title: "White Boy Rick", status: "watched" },
  { id: "american-made", title: "American Made", status: "watched" },
  { id: "mr-mrs-smith", title: "Mr. & Mrs. Smith", status: "watched" },
  { id: "conspiracy-theory", title: "Conspiracy Theory", status: "watched" },
  { id: "freerunner", title: "Freerunner", status: "watched" },
  { id: "minority-report", title: "Minority Report", status: "watched" },
  { id: "elysium", title: "Elysium", status: "watched" },
  { id: "now-you-see-me", title: "Now You See Me", status: "watched" },
  { id: "the-sixth-sense", title: "The Sixth Sense", status: "watched" },
  { id: "game-night", title: "Game Night", status: "watched" },
  { id: "13-hours", title: "13 Hours", status: "watched" },
  { id: "world-war-z", title: "World War Z", status: "watched" },
  { id: "snatch", title: "Snatch", status: "watched" },
  { id: "django-unchained", title: "Django Unchained", status: "watched" },
  { id: "sinbad", title: "Sinbad", status: "watched" },
  { id: "catch-me-if-you-can", title: "Catch Me If You Can", status: "watched" },
  { id: "tag", title: "Tag", status: "watched" },
  { id: "after-earth", title: "After Earth", status: "watched" },
  { id: "the-dark-knight-trilogy", title: "The Dark Knight Trilogy", status: "watched", count: 3 },
  { id: "fight-club", title: "Fight Club", status: "watched" },
  { id: "alita-battle-angel", title: "Alita: Battle Angel", status: "watched" },
  { id: "300", title: "300", status: "watched" },
  { id: "gladiator", title: "Gladiator", status: "watched" },
  { id: "the-patriot", title: "The Patriot", status: "watched" },
  { id: "i-am-legend", title: "I Am Legend", status: "watched" },
  { id: "eraser", title: "Eraser", status: "watched" },
  { id: "predator", title: "Predator", status: "watched" },
  { id: "braveheart", title: "Braveheart", status: "watched" },
  { id: "mcfarland-usa", title: "McFarland, USA", status: "watched" },
  { id: "the-big-short", title: "The Big Short", status: "watched" },
  { id: "security", title: "Security", status: "watched" },
  { id: "robocop", title: "RoboCop", status: "watched" },
  { id: "snowpiercer", title: "Snowpiercer", status: "watched" },
  { id: "the-adam-project", title: "The Adam Project", status: "watched" },
  { id: "don-t-look-up", title: "Don't Look Up", status: "watched" },
  { id: "hacksaw-ridge", title: "Hacksaw Ridge", status: "watched" },
  { id: "click", title: "Click", status: "watched" },
  { id: "the-social-network", title: "The Social Network", status: "watched" },
  { id: "exodus-gods-and-kings", title: "Exodus: Gods and Kings", status: "watched" },
  { id: "tomorrowland", title: "Tomorrowland", status: "watched" },
  { id: "nerve", title: "Nerve", status: "watched" },
  { id: "gran-turismo", title: "Gran Turismo", status: "watched" },
  { id: "zoolander", title: "Zoolander", status: "watched" },
  { id: "baby-driver", title: "Baby Driver", status: "watched" },
  { id: "the-quick-and-the-dead", title: "The Quick and the Dead", status: "watched" },
  { id: "yes-man", title: "Yes Man", status: "watched" },
  { id: "focus", title: "Focus", status: "watched" },
  { id: "carry-on", title: "Carry-On", status: "watched" },
  { id: "blackkklansman", title: "BlacKkKlansman", status: "watched" },
  { id: "no-country-for-old-men", title: "No Country for Old Men", status: "watched" },
  { id: "the-ballad-of-buster-scruggs", title: "The Ballad of Buster Scruggs", status: "watched" },
  { id: "crazy-stupid-love", title: "Crazy, Stupid, Love.", status: "watched" },
  { id: "where-the-crawdads-sing", title: "Where the Crawdads Sing", status: "watched" },
  { id: "her", title: "Her", status: "watched" },
  { id: "awakenings", title: "Awakenings", status: "watched" },
  { id: "the-dawn-wall", title: "The Dawn Wall", status: "watched" },
  { id: "fahrenheit-451", title: "Fahrenheit 451", status: "watched" },
  { id: "pulp-fiction", title: "Pulp Fiction", status: "watched" },
  { id: "f1-the-movie", title: "F1: The Movie", status: "watched" },
  { id: "valley-uprising", title: "Valley Uprising", status: "watched" },
  { id: "the-secret-life-of-walter-mitty", title: "The Secret Life of Walter Mitty", status: "watched" },
  { id: "ad-astra", title: "Ad Astra", status: "watched" },
  { id: "barbarian", title: "Barbarian", status: "watched" },
  { id: "in-time", title: "In Time", status: "watched" },
  { id: "imperium", title: "Imperium", status: "watched" },
  { id: "mickey-17", title: "Mickey 17", status: "watched" },
  { id: "idiocracy", title: "Idiocracy", status: "watched" },
  { id: "se7en", title: "Se7en", status: "watched" },
  { id: "horrible-bosses", title: "Horrible Bosses", status: "watched" },
  { id: "collateral", title: "Collateral", status: "watched" },
  { id: "inside-man", title: "Inside Man", status: "watched" },
  { id: "looper", title: "Looper", status: "watched" },
  { id: "arrival", title: "Arrival", status: "watched" },
  { id: "whiplash", title: "Whiplash", status: "watched" },
  { id: "saving-private-ryan", title: "Saving Private Ryan", status: "watched" },
  { id: "the-matrix", title: "The Matrix", status: "watched", count: 4 },
  { id: "the-equalizer-2", title: "The Equalizer 2", status: "watched" },
  { id: "inside-man-most-wanted", title: "Inside Man: Most Wanted", status: "watched" },
  { id: "the-italian-job", title: "The Italian Job", status: "watched" },
  { id: "jack-reacher", title: "Jack Reacher", status: "watched" },
  { id: "black-hawk-down", title: "Black Hawk Down", status: "watched" },
  { id: "fury", title: "Fury", status: "watched" },
  { id: "jarhead", title: "Jarhead", status: "watched" },
  { id: "oblivion", title: "Oblivion", status: "watched" },
  { id: "district-9", title: "District 9", status: "watched" },
  { id: "total-recall", title: "Total Recall", status: "watched", count: 2 },
  { id: "terminator", title: "Terminator", status: "watched", series: true },
  { id: "alien-vs-predator", title: "Alien vs. Predator", status: "watched", series: true },
  { id: "edge-of-tomorrow", title: "Edge of Tomorrow", status: "watched" },
  { id: "star-wars", title: "Star Wars", status: "watched", series: true },
  { id: "inception", title: "Inception", status: "watched" },
  { id: "interstellar", title: "Interstellar", status: "watched" },
  { id: "the-bourne-trilogy", title: "The Bourne Trilogy", status: "watched", count: 3 },
  { id: "forrest-gump", title: "Forrest Gump", status: "watched" },
  { id: "the-truman-show", title: "The Truman Show", status: "watched" },
  { id: "good-will-hunting", title: "Good Will Hunting", status: "watched" },
  { id: "the-wolf-of-wall-street", title: "The Wolf of Wall Street", status: "watched" },
  { id: "superbad", title: "Superbad", status: "watched" },
  { id: "21-jump-street", title: "21 Jump Street", status: "watched" },
  { id: "white-house-down", title: "White House Down", status: "watched" },
  { id: "commando", title: "Commando", status: "watched" },
  { id: "the-running-man", title: "The Running Man", status: "watched" },
  { id: "last-action-hero", title: "Last Action Hero", status: "watched" },
  { id: "true-lies", title: "True Lies", status: "watched" },
  { id: "end-of-days", title: "End of Days", status: "watched" },
  { id: "collateral-damage", title: "Collateral Damage", status: "watched" },
  { id: "twins", title: "Twins", status: "watched" },
  { id: "kindergarten-cop", title: "Kindergarten Cop", status: "watched" },
  { id: "junior", title: "Junior", status: "watched" },
  { id: "jingle-all-the-way", title: "Jingle All the Way", status: "watched" },
  { id: "the-expendables", title: "The Expendables", status: "watched" },
  { id: "escape-plan", title: "Escape Plan", status: "watched" },
  { id: "killing-gunther", title: "Killing Gunther", status: "watched" },
  { id: "batman-robin", title: "Batman & Robin", status: "watched" },
  { id: "aftermath", title: "Aftermath", status: "watched" },
  { id: "mad-max", title: "Mad Max", status: "watched", series: true },
  { id: "law-abiding-citizen", title: "Law Abiding Citizen", status: "watched" },
  { id: "avatar", title: "Avatar", status: "watched" },
  { id: "iron-man", title: "Iron Man", status: "watched", count: 3 },
  { id: "captain-america", title: "Captain America", status: "watched", count: 3 },
  { id: "the-avengers", title: "The Avengers", status: "watched", count: 4 },
  { id: "thor", title: "Thor", status: "watched", count: 4 },
  { id: "guardians-of-the-galaxy", title: "Guardians of the Galaxy", status: "watched", count: 3 },
  { id: "doctor-strange", title: "Doctor Strange", status: "watched" },
  { id: "black-panther", title: "Black Panther", status: "watched" },
  { id: "ant-man", title: "Ant-Man", status: "watched" },
  { id: "deadpool", title: "Deadpool", status: "watched" },
  { id: "x-men", title: "X-Men", status: "watched" },
  { id: "venom", title: "Venom", status: "watched" },
  { id: "logan", title: "Logan", status: "watched" },
  { id: "man-of-steel", title: "Man of Steel", status: "watched" },
  { id: "batman-v-superman-dawn-of-justice", title: "Batman v Superman: Dawn of Justice", status: "watched" },
  { id: "zack-snyder-s-justice-league", title: "Zack Snyder's Justice League", status: "watched" },
  { id: "wonder-woman", title: "Wonder Woman", status: "watched" },
  { id: "aquaman", title: "Aquaman", status: "watched" },
  { id: "shazam", title: "Shazam!", status: "watched", count: 2 },
  { id: "suicide-squad", title: "Suicide Squad", status: "watched" },
  { id: "joker", title: "Joker", status: "watched" },
  { id: "here-comes-the-boom", title: "Here Comes the Boom", status: "watched" },
  { id: "zookeeper", title: "Zookeeper", status: "watched" },
  { id: "school-of-rock", title: "School of Rock", status: "watched" },
  { id: "kung-fu-panda", title: "Kung Fu Panda", status: "watched", series: true },
  { id: "shrek", title: "Shrek", status: "watched", series: true },
  { id: "inside-out", title: "Inside Out", status: "watched" },
  { id: "deadpool-wolverine", title: "Deadpool & Wolverine", status: "watched" },
  { id: "despicable-me", title: "Despicable Me", status: "watched", count: 3 },
  { id: "a-quiet-place", title: "A Quiet Place", status: "watched" },
  { id: "twister", title: "Twister", status: "watched" },
  { id: "dune", title: "Dune", status: "watched", count: 2 },
  { id: "the-fall-guy", title: "The Fall Guy", status: "watched" },
  { id: "oppenheimer", title: "Oppenheimer", status: "watched" },
  { id: "ant-man-and-the-wasp", title: "Ant-Man and the Wasp", status: "watched", count: 2 },
  { id: "the-nun", title: "The Nun", status: "watched" },
  { id: "the-meg", title: "The Meg", status: "watched" },
  { id: "cocaine-bear", title: "Cocaine Bear", status: "watched" },
  { id: "saw", title: "Saw", status: "watched", count: 10 },
  { id: "napoleon", title: "Napoleon", status: "watched" },
  { id: "avatar-the-way-of-water", title: "Avatar: The Way of Water", status: "watched" },
  { id: "the-batman", title: "The Batman", status: "watched" },
  { id: "elvis", title: "Elvis", status: "watched" },
  { id: "bullet-train", title: "Bullet Train", status: "watched" },
  { id: "smile", title: "Smile", status: "watched" },
  { id: "free-guy", title: "Free Guy", status: "watched" },
  { id: "aladdin", title: "Aladdin", status: "watched" },
  { id: "jumanji", title: "Jumanji", status: "watched", count: 3 },
  { id: "it", title: "It", status: "watched", count: 4 },
  { id: "ford-v-ferrari", title: "Ford v Ferrari", status: "watched" },
  { id: "1917", title: "1917", status: "watched" },
  { id: "glass", title: "Glass", status: "watched" },
  { id: "moana", title: "Moana", status: "watched" },
  { id: "split", title: "Split", status: "watched" },
  { id: "hamilton", title: "Hamilton", status: "watched" },
  { id: "free-solo", title: "Free Solo", status: "watched" },
  { id: "wonka", title: "Wonka", status: "watched" },
  { id: "the-shining", title: "The Shining", status: "watched" },
  { id: "this-is-the-end", title: "This Is the End", status: "watched" },
  { id: "the-butterfly-effect", title: "The Butterfly Effect", status: "watched" },
  { id: "get-out", title: "Get Out", status: "watched" },
  { id: "hellboy", title: "Hellboy", status: "watched" },
  { id: "zombieland", title: "Zombieland", status: "watched" },
  { id: "bird-box", title: "Bird Box", status: "watched" },
  { id: "the-happening", title: "The Happening", status: "watched" },
  { id: "the-conjuring", title: "The Conjuring", status: "watched" },
  { id: "halloween", title: "Halloween", status: "watched" },
  { id: "a-nightmare-on-elm-street", title: "A Nightmare on Elm Street", status: "watched" },
  { id: "the-silence-of-the-lambs", title: "The Silence of the Lambs", status: "watched" },
  { id: "gremlins", title: "Gremlins", status: "watched" },
  { id: "dumb-and-dumber", title: "Dumb and Dumber", status: "watched" },
  { id: "groundhog-day", title: "Groundhog Day", status: "watched" },
  { id: "superman", title: "Superman", status: "watched" },
  { id: "american-sniper", title: "American Sniper", status: "watched" },
  { id: "maggie", title: "Maggie", status: "watched" },
  { id: "a-man-called-otto", title: "A Man Called Otto", status: "watched" },
  { id: "the-gentlemen", title: "The Gentlemen", status: "watched" },
  { id: "the-gorge", title: "The Gorge", status: "watched" },
  { id: "tetris", title: "Tetris", status: "watched" },
  { id: "life", title: "Life", status: "watched" },
  { id: "absolutely-anything", title: "Absolutely Anything", status: "watched" },
  { id: "the-amateur", title: "The Amateur", status: "watched" },
  { id: "the-long-walk", title: "The Long Walk", status: "watched" },
  { id: "i-love-you-man", title: "I Love You, Man", status: "watched" },
  { id: "tropic-thunder", title: "Tropic Thunder", status: "watched" },
  { id: "it-miniseries", title: "It (miniseries)", status: "watched" },
  { id: "28-days-later", title: "28 Days Later", status: "watched" },
  { id: "28-weeks-later", title: "28 Weeks Later", status: "watched" },
  { id: "28-years-later", title: "28 Years Later", status: "watched" },
  { id: "tron-ares", title: "Tron: Ares", status: "watched" },
  { id: "code-3", title: "Code 3", status: "watched" },
  { id: "the-menu", title: "The Menu", status: "watched" },
  { id: "honey-don-t", title: "Honey Don't!", status: "watched" },
  { id: "caught-stealing", title: "Caught Stealing", status: "watched" },
  { id: "source-code", title: "Source Code", status: "watched" },
  { id: "greenland", title: "Greenland", status: "watched" },
  { id: "greenland-migration", title: "Greenland: Migration", status: "watched" },
  { id: "zodiac", title: "Zodiac", status: "watched" },
  { id: "jurassic-world", title: "Jurassic World", status: "watched" },
  { id: "jurassic-world-fallen-kingdom", title: "Jurassic World: Fallen Kingdom", status: "watched" },
  { id: "jurassic-world-dominion", title: "Jurassic World Dominion", status: "watched" },
  { id: "jurassic-world-rebirth", title: "Jurassic World Rebirth", status: "watched" },
  { id: "jurassic-park", title: "Jurassic Park", status: "watched" },
  { id: "the-lost-world-jurassic-park", title: "The Lost World: Jurassic Park", status: "watched" },
  { id: "jurassic-park-iii", title: "Jurassic Park III", status: "watched" },
  { id: "daybreak", title: "Daybreak", status: "watched" },
  { id: "mercy", title: "Mercy", status: "watched" },
  { id: "the-backrooms", title: "The Backrooms", status: "watched" },
  { id: "the-odyssey", title: "The Odyssey", status: "watched" },
  { id: "spider-man-brand-new-day", title: "Spider-Man: Brand New Day", status: "watched" },
  { id: "obsession", title: "Obsession", status: "watched" },
  { id: "rush", title: "Rush", status: "watchlist", where: "Buy" },
  { id: "curtis", title: "Curtis", status: "watchlist", where: "Buy" },
  { id: "lamborghini", title: "Lamborghini", status: "watchlist", where: "Buy" },
  { id: "the-angriest-man-in-brooklyn", title: "The Angriest Man in Brooklyn", status: "watchlist", where: "Starz" },
  { id: "four-brothers", title: "Four Brothers", status: "watchlist", where: "Buy" },
  { id: "lone-survivor", title: "Lone Survivor", status: "watchlist", where: "Prime Video" },
  { id: "american-honey", title: "American Honey", status: "watchlist", where: "Prime Video" },
  { id: "seven-pounds", title: "Seven Pounds", status: "watchlist", where: "Buy" },
  { id: "knowing", title: "Knowing", status: "watchlist", where: "Pluto TV" },
  { id: "we-are-your-friends", title: "We Are Your Friends", status: "watchlist", where: "Buy" },
  { id: "triangle", title: "Triangle", status: "watchlist", where: "Tubi" },
  { id: "no-hard-feelings", title: "No Hard Feelings", status: "watchlist", where: "Hulu", pick: true },
  { id: "the-notebook", title: "The Notebook", status: "watchlist", where: "Buy", pick: true },
  { id: "the-prestige", title: "The Prestige", status: "watchlist", where: "Buy" },
  { id: "the-departed", title: "The Departed", status: "watchlist", where: "Buy" },
  { id: "v-for-vendetta", title: "V for Vendetta", status: "watchlist", pick: true },
  { id: "the-wall", title: "The Wall", status: "watchlist", where: "Prime Video" },
  { id: "samaritan", title: "Samaritan", status: "watchlist" },
  { id: "training-day", title: "Training Day", status: "watchlist" },
  { id: "you-should-have-left", title: "You Should Have Left", status: "watchlist" },
  { id: "taxi-driver", title: "Taxi Driver", status: "watchlist" },
  { id: "the-family-plan", title: "The Family Plan", status: "watchlist" },
  { id: "what-women-want", title: "What Women Want", status: "watchlist" },
  { id: "unstoppable", title: "Unstoppable", status: "watchlist" },
  { id: "greater-good", title: "Greater Good", status: "watchlist" },
  { id: "the-hunt", title: "The Hunt", status: "watchlist" },
  { id: "equilibrium", title: "Equilibrium", status: "watchlist", where: "Buy" },
  { id: "mayhem", title: "Mayhem", status: "watchlist", where: "Plex / Tubi" },
  { id: "heathers", title: "Heathers", status: "watchlist", pick: true },
  { id: "the-jester", title: "The Jester", status: "watchlist" },
  { id: "pawn-sacrifice", title: "Pawn Sacrifice", status: "watchlist" },
  { id: "finch", title: "Finch", status: "watchlist", where: "Apple TV+" },
  { id: "next", title: "Next", status: "watchlist", where: "Buy" },
  { id: "adaptation", title: "Adaptation", status: "watchlist" },
  { id: "10-cloverfield-lane", title: "10 Cloverfield Lane", status: "watchlist", pick: true },
  { id: "argo", title: "Argo", status: "watchlist", where: "Peacock" },
  { id: "man-on-fire", title: "Man on Fire", status: "watchlist" },
  { id: "green-book", title: "Green Book", status: "watchlist", where: "Buy" },
  { id: "carriers", title: "Carriers", status: "watchlist" },
  { id: "premium-rush", title: "Premium Rush", status: "watchlist" },
  { id: "all-eyez-on-me", title: "All Eyez on Me", status: "watchlist" },
  { id: "my-name-is-earl", title: "My Name Is Earl", status: "watchlist" },
  { id: "end-of-watch", title: "End of Watch", status: "watchlist" },
  { id: "only-the-brave", title: "Only the Brave", status: "watchlist" },
  { id: "men-of-honor", title: "Men of Honor", status: "watchlist" },
  { id: "the-aviator", title: "The Aviator", status: "watchlist" },
  { id: "sin-city", title: "Sin City", status: "watchlist" },
  { id: "the-day-of-the-jackal", title: "The Day of the Jackal", status: "watchlist" },
  { id: "downsizing", title: "Downsizing", status: "watchlist" },
  { id: "kill-bill", title: "Kill Bill", status: "watchlist", where: "Pluto TV", pick: true },
  { id: "three-thousand-years-of-longing", title: "Three Thousand Years of Longing", status: "watchlist" },
  { id: "the-taking-of-pelham-one-two-three", title: "The Taking of Pelham One Two Three", status: "watchlist" },
  { id: "moneyball", title: "Moneyball", status: "watchlist" },
  { id: "the-sound", title: "The Sound", status: "watchlist" },
  { id: "a-i-rising", title: "A.I. Rising", status: "watchlist" },
  { id: "the-town", title: "The Town", status: "watchlist" },
  { id: "a-prayer-before-dawn", title: "A Prayer Before Dawn", status: "watchlist" },
  { id: "jungle", title: "Jungle", status: "watchlist", where: "Prime Video" },
  { id: "into-the-blue", title: "Into the Blue", status: "watchlist" },
  { id: "speed", title: "Speed", status: "watchlist", where: "HBO Max" },
  { id: "friendship", title: "Friendship", status: "watchlist" },
  { id: "the-impossible", title: "The Impossible", status: "watchlist" },
  { id: "the-roses", title: "The Roses", status: "watchlist" },
  { id: "inglourious-basterds", title: "Inglourious Basterds", status: "watchlist", pick: true },
  { id: "blended", title: "Blended", status: "watchlist" },
  { id: "if-only", title: "If Only", status: "watchlist" },
  { id: "odd-thomas", title: "Odd Thomas", status: "watchlist" },
  { id: "magazine-dreams", title: "Magazine Dreams", status: "watchlist" },
  { id: "the-whale", title: "The Whale", status: "watchlist" },
  { id: "demolition", title: "Demolition", status: "watchlist", where: "Hulu" },
  { id: "the-heartbreak-kid", title: "The Heartbreak Kid", status: "watchlist" },
  { id: "another-earth", title: "Another Earth", status: "watchlist" },
  { id: "the-flash", title: "The Flash", status: "watchlist" },
  { id: "wanted", title: "Wanted", status: "watchlist", where: "Buy" },
  { id: "where-hope-grows", title: "Where Hope Grows", status: "watchlist" },
  { id: "john-wick", title: "John Wick", status: "watchlist", where: "Buy", pick: true },
  { id: "goodfellas", title: "Goodfellas", status: "watchlist", pick: true },
  { id: "casino", title: "Casino", status: "watchlist" },
  { id: "scarface", title: "Scarface", status: "watchlist", pick: true },
  { id: "moments", title: "Moments", status: "watchlist" },
  { id: "the-machinist", title: "The Machinist", status: "watchlist" },
  { id: "blade-runner", title: "Blade Runner", status: "watchlist" },
  { id: "2001-a-space-odyssey", title: "2001: A Space Odyssey", status: "watchlist" },
  { id: "the-godfather", title: "The Godfather", status: "watchlist", pick: true },
  { id: "talladega-nights", title: "Talladega Nights", status: "watchlist" },
  { id: "shutter-island", title: "Shutter Island", status: "watchlist", pick: true },
  { id: "children-of-men", title: "Children of Men", status: "watchlist" },
  { id: "greater", title: "Greater", status: "watchlist" },
  { id: "the-room", title: "The Room", status: "watchlist" },
  { id: "kiss-kiss-bang-bang", title: "Kiss Kiss Bang Bang", status: "watchlist" },
  { id: "shooter", title: "Shooter", status: "watchlist" },
  { id: "the-losers", title: "The Losers", status: "watchlist" },
  { id: "the-ministry-of-ungentlemanly-warfare", title: "The Ministry of Ungentlemanly Warfare", status: "watchlist" },
  { id: "the-others", title: "The Others", status: "watchlist" },
  { id: "shaun-of-the-dead", title: "Shaun of the Dead", status: "watchlist", where: "Buy" },
  { id: "anaconda", title: "Anaconda", status: "watchlist" },
  { id: "flight-risk", title: "Flight Risk", status: "watchlist" },
  { id: "guns-akimbo", title: "Guns Akimbo", status: "watchlist" },
  { id: "marty-supreme", title: "Marty Supreme", status: "watchlist" },
  { id: "roofman", title: "Roofman", status: "watchlist" },
  { id: "the-revenant", title: "The Revenant", status: "watchlist" },
  { id: "the-place-beyond-the-pines", title: "The Place Beyond the Pines", status: "watchlist" },
  { id: "ray", title: "Ray", status: "watchlist" },
  { id: "ghosted", title: "Ghosted", status: "watchlist" },
  { id: "tommy-boy", title: "Tommy Boy", status: "watchlist" },
  { id: "the-devil-s-advocate", title: "The Devil's Advocate", status: "watchlist" },
  { id: "send-help", title: "Send Help", status: "watchlist" },
  { id: "smokey-and-the-bandit", title: "Smokey and the Bandit", status: "watchlist" },
  { id: "rip", title: "RIP", status: "watchlist" },
  { id: "the-master", title: "The Master", status: "watchlist" },
  { id: "just-friends", title: "Just Friends", status: "watchlist" },
  { id: "boss-level", title: "Boss Level", status: "watchlist" },
  { id: "knives-out", title: "Knives Out", status: "watchlist" },
  { id: "ruby-sparks", title: "Ruby Sparks", status: "watchlist" },
  { id: "pumping-iron", title: "Pumping Iron", status: "watchlist" },
  { id: "the-dark-tower", title: "The Dark Tower", status: "watchlist" },
  { id: "hypnotic", title: "Hypnotic", status: "watchlist" },
  { id: "heat", title: "Heat", status: "watchlist" },
  { id: "fallen", title: "Fallen", status: "watchlist" },
  { id: "war-machine", title: "War Machine", status: "watchlist" },
  { id: "the-adventures-of-tintin", title: "The Adventures of Tintin", status: "watchlist" },
  { id: "what-happened-to-monday", title: "What Happened to Monday", status: "watchlist" },
  { id: "lawless", title: "Lawless", status: "watchlist" },
  { id: "we-live-in-time", title: "We Live in Time", status: "watchlist" },
  { id: "nightcrawler", title: "Nightcrawler", status: "watchlist" },
];
