/* CROSSFIRE — room service, the part that thinks
   ────────────────────────────────────────────────────────────────────────────
   Online play is a list of open games, and this holds it. A host opens a room
   and it appears in everybody's list; a guest clicks it, gives the password if
   there is one, and the two connection descriptions are handed across here.
   Nobody ever sees or carries a code.

   It sees no gameplay. Once two peers are connected they talk directly and
   nothing else comes through here — a room is thirty seconds of matchmaking,
   not a server the match depends on. But it is the only way in, so with this
   down there is no online play, and the game says so rather than pretending.

   ── why this file exists apart from the two that run it ──
   The service runs in two places: on Cloudflare for everybody, and on a laptop
   for whoever is working on it. Those two need completely different plumbing —
   one is a Durable Object, the other is a node:http server — but they must
   agree exactly on who is allowed in, what a password is worth and when a room
   dies. Written twice, the second copy silently stops matching the first, and
   the half that rots is the half nobody tests. So it is written once, here,
   against nothing but Request, Response and Web Crypto, which both runtimes
   have. `worker.mjs` and `rooms.js` are plumbing and hold no rules.

   ── state ──
   Everything lives in memory and expires. There is no database, nothing is
   written to disk, and being restarted — or, on Cloudflare, evicted — throws
   away every room. That costs nobody anything: a room only exists while
   somebody is sitting in a lobby with it open, and the host's next heartbeat
   builds its room again from scratch.                                        */

/* Which sites may talk to this. A browser will refuse to send the request at
   all unless the origin is echoed back, so this is the guest list. */
export const ALLOWED = new Set([
  "https://ricmassey.com",
  "https://www.ricmassey.com",
  "https://ric-massey.github.io",
  "http://localhost:8000",
  "http://127.0.0.1:8000",
  "http://localhost:8912"          // alternate local preview port
]);

const ROOM_TTL   = 25_000;   // a room with no heartbeat this long is gone
const JOIN_TTL   = 60_000;   // an unanswered join request expires
const MAX_ROOMS  = 200;
const MAX_JOINS  = 8;        // pending joins per room
const MAX_BODY   = 12 * 1024; // includes an uncompressed full-SDP fallback

/* A room id is generated by the host's browser and never typed by anyone — the
   list is how you find a game now, so the id only has to be unique and safe in
   a URL. It is NOT a secret: everything about a room is public except its
   password, and the id is what a guest clicks. */
const WORD_RE = /^[a-z0-9][a-z0-9-]{1,23}$/;
const tidyWord = w => String(w || "").trim().toLowerCase();

/* What the room is called in the list. This is the one piece of a room that
   strangers read, so it is cut to size and stripped of anything that isn't
   plainly a name. The game draws it with textContent, never as markup. */
const TITLE_MAX = 24;
const tidyTitle = t =>
  String(t == null ? "" : t)
    .replace(/[^\p{L}\p{N} '\-!?.]/gu, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, TITLE_MAX);

const tidyName = n =>
  String(n == null ? "" : n).replace(/[^\p{L}\p{N} '-]/gu, "").trim().slice(0, 12);

// Descriptions are opaque here — they're the game's own compact codes, and
// this only checks that they're the right shape and size to be one.
const looksLikeCode = c =>
  typeof c === "string" && c.length > 8 && c.length < 7_500 && /^[\w+/=]+$/.test(c);

/* ── passwords ───────────────────────────────────────────────────────────────
   A lobby password is a short thing typed by a friend, not a credential, and
   it lives for the twenty-five seconds a room does. It is still never stored
   as itself: the room keeps a salted hash and a constant-time comparison.

   The hash is fast, which on its own would be weak — so the real defence is
   the attempt limiter below. A room that fails PASS_TRIES passwords inside
   PASS_WINDOW stops answering guesses entirely, which turns even a four-letter
   password into something nobody is going to walk through in the half minute
   the room exists for.

   Web Crypto rather than node:crypto because a Worker has no node:crypto, and
   the digest is async there — which is why everything downstream of a password
   check is too. */
const PASS_MAX = 24;
const PASS_TRIES = 8;
const PASS_WINDOW = 60_000;

const enc = new TextEncoder();

async function hashPass(pass, salt) {
  const bits = await crypto.subtle.digest("SHA-256", enc.encode(salt + ":" + pass));
  return new Uint8Array(bits);
}

async function makePass(raw) {
  const pass = String(raw == null ? "" : raw).slice(0, PASS_MAX);
  if (!pass) return null;
  const bytes = crypto.getRandomValues(new Uint8Array(16));
  const salt = [...bytes].map(b => b.toString(16).padStart(2, "0")).join("");
  return { salt, hash: await hashPass(pass, salt) };
}

/* Both digests are the same length, so this reads all of both and leaks only
   that fact. Node has timingSafeEqual for this; a Worker does not. */
function sameBytes(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

async function passOk(room, raw) {
  if (!room.pass) return true;
  const given = await hashPass(
    String(raw == null ? "" : raw).slice(0, PASS_MAX), room.pass.salt
  );
  return sameBytes(given, room.pass.hash);
}

// Returns false once a room has had too many wrong passwords too quickly.
function passAllow(room) {
  const now = Date.now();
  if (!room.fails || now - room.fails.at > PASS_WINDOW) {
    room.fails = { n: 0, at: now };
  }
  return room.fails.n < PASS_TRIES;
}

/* ── plumbing ───────────────────────────────────────────────────────────── */
function send(code, body, origin) {
  const headers = {
    "content-type": "application/json; charset=utf-8",
    "cache-control": "no-store",
    "vary": "origin"
  };
  if (origin) headers["access-control-allow-origin"] = origin;
  return new Response(JSON.stringify(body), { status: code, headers });
}

/* A body is read at most once and never past MAX_BODY. content-length is a
   claim rather than a fact, so it is used to refuse the obvious cases early
   and the decoded length is checked again afterwards. */
async function readBody(request) {
  const claimed = Number(request.headers.get("content-length") || 0);
  if (claimed > MAX_BODY) throw new Error("too big");
  const text = await request.text();
  if (!text) return {};
  if (text.length > MAX_BODY) throw new Error("too big");
  return JSON.parse(text);
}

/* ── the service ────────────────────────────────────────────────────────────
   One instance holds every room. On Cloudflare that is one Durable Object, so
   there is exactly one of these in the world and no two hosts can ever see
   different lists. It sits in one region and everybody else's lobby polls
   cross an ocean to reach it, which for picking a game off a list nobody will
   ever feel — and the match itself never comes near it.                     */
export function createRooms() {
  /* id → { host: the owner's key, seen: last heartbeat, joins: Map(id → join),
            name: the host player's name, title: what the room is called,
            pass: null or { salt, hash }, players, max,
            listed: whether it belongs in the public list,
            fails: wrong-password counter }                                  */
  const rooms = new Map();

  /* A public list invites poking at it, so make every request cost. A leaky
     bucket per address.

     The numbers have to be read as a household rather than a person, because
     an address is a house: everybody on one wifi arrives here as the same
     caller, and a game for friends and family is mostly two people on one
     sofa. So count the worst sensible room — five players, one router:

         the host beats every 2s                        30/min
         four guests refresh the list every 3s          80/min
         each guest, while joining, polls every 0.5s    a burst of 20

     which is about 110 a minute before anybody has done anything unusual. The
     first version of this allowed 30 a minute, so a host on its own sat exactly
     on the ceiling and two people in the same house pushed each other off it
     inside a minute — throttling the family out of their own game. 4/s
     sustained is roughly double what that room needs.

     Loosening this costs nothing in password security: guessing is held by the
     per-room limiter above, which allows 8 wrong answers a minute no matter how
     fast they arrive, and a room only lives twenty-five seconds. This bucket is
     only here so that flooding the list is dull. */
  const buckets = new Map();
  const RATE = { size: 120, refillMs: 250 };

  let seq = 0;
  const newId = () => (++seq).toString(36) + Date.now().toString(36).slice(-4);

  /* Sweeping on the way in rather than on a timer. The runtimes disagree about
     what a long-lived timer is worth — a Worker would rather be asleep — and
     nothing here needs a room to disappear at any particular moment, only for
     an expired one to never be answered for or counted. */
  function reap() {
    const now = Date.now();
    for (const [word, room] of rooms) {
      if (now - room.seen > ROOM_TTL) { rooms.delete(word); continue; }
      for (const [id, join] of room.joins) {
        if (now - join.at > JOIN_TTL) room.joins.delete(id);
      }
    }
    for (const [ip, b] of buckets) if (now - b.at > 120_000) buckets.delete(ip);
  }

  function allow(ip) {
    const now = Date.now();
    let b = buckets.get(ip);
    if (!b) { b = { tokens: RATE.size, at: now }; buckets.set(ip, b); }
    b.tokens = Math.min(RATE.size, b.tokens + (now - b.at) / RATE.refillMs);
    b.at = now;
    if (b.tokens < 1) return false;
    b.tokens -= 1;
    return true;
  }

  /* ── the things it can do ─────────────────────────────────────────────────
     `ip` is worked out by whichever runtime is calling, because only it knows
     which header to believe. Nothing in here trusts an address off the wire. */
  async function handle(request, ip) {
    const origin = request.headers.get("origin");
    const allowedOrigin = ALLOWED.has(origin) ? origin : null;

    // Requests without Origin are health checks or command-line tools. Browser
    // requests must be on the allowlist; do not make `Origin: null` a back door.
    if (origin && !allowedOrigin) {
      return send(403, { error: "origin not allowed" }, null);
    }

    if (request.method === "OPTIONS") {
      const headers = {
        "access-control-allow-methods": "GET, POST, OPTIONS",
        "access-control-allow-headers": "content-type",
        "access-control-max-age": "86400",
        "vary": "origin"
      };
      if (allowedOrigin) headers["access-control-allow-origin"] = allowedOrigin;
      return new Response(null, { status: 204, headers });
    }

    reap();

    const url = new URL(request.url);
    const parts = url.pathname.split("/").filter(Boolean);

    // Is anybody home? The game asks this before it offers a list at all, and
    // says online play is off when it doesn't answer.
    if (request.method === "GET" && parts[0] === "health") {
      return send(200, { ok: true, rooms: rooms.size }, allowedOrigin);
    }

    if (!allow(ip)) return send(429, { error: "slow down" }, allowedOrigin);

    /* The list. Everything here is meant to be seen by strangers — the password
       and its salt never leave this process, and a locked room says only that it
       is locked. A room that has started, or filled up, asks not to be listed. */
    if (request.method === "GET" && parts[0] === "rooms") {
      const open = [];
      for (const [id, room] of rooms) {
        if (room.listed === false) continue;
        open.push({
          id,
          title: room.title || "a game",
          host: room.name || "",
          mode: room.mode || "survival",
          players: room.players || 1,
          max: room.max || 5,
          locked: !!room.pass
        });
      }
      return send(200, { ok: true, rooms: open }, allowedOrigin);
    }

    const word = tidyWord(parts[1]);
    if (parts[0] !== "room" || !WORD_RE.test(word)) {
      return send(404, { error: "no such thing" }, allowedOrigin);
    }

    let body = {};
    if (request.method === "POST") {
      try { body = await readBody(request); }
      catch (_) { return send(400, { error: "bad body" }, allowedOrigin); }
    }

    /* Host: claim the id, and collect anybody waiting at the door. One call
       does both, so the host's polling loop is a single request. */
    if (request.method === "POST" && parts[2] === "host") {
      let room = rooms.get(word);
      const me = String(body.key || "");
      if (!me) return send(400, { error: "no key" }, allowedOrigin);

      if (room && room.host !== me) {
        return send(409, { error: "that room name is in use" }, allowedOrigin);
      }
      if (!room) {
        if (rooms.size >= MAX_ROOMS) {
          return send(503, { error: "too many rooms" }, allowedOrigin);
        }
        room = { host: me, seen: 0, joins: new Map(), name: "",
                 title: "", pass: null, mode: "survival",
                 players: 1, max: 5, listed: true };
        rooms.set(word, room);
      }
      room.host = me;
      room.seen = Date.now();
      room.name = tidyName(body.name);
      room.title = tidyTitle(body.title) || room.title;
      // The mode is a label to this service; the game decides what it means.
      if (typeof body.mode === "string" && /^[a-z]{1,16}$/.test(body.mode)) {
        room.mode = body.mode;
      }
      room.players = Math.max(1, Math.min(16, Number(body.players) || 1));
      room.max = Math.max(1, Math.min(16, Number(body.max) || 5));
      room.listed = body.listed !== false;

      /* The password travels with the heartbeat rather than only at creation, so
         the host can lock or unlock a room without tearing it down. Only the key
         that owns the room gets here, and a room is re-salted every time it is
         set — an unchanged password still gets a fresh hash. */
      if (typeof body.pass === "string") {
        room.pass = await makePass(body.pass);
        room.fails = null;
      }

      // Hand over the waiting offers and forget them: the host answers each one
      // and posts the answers back, so nothing needs to be kept here.
      const joins = [];
      for (const [id, join] of room.joins) {
        if (join.offer && !join.taken) {
          join.taken = true;
          joins.push({ id, offer: join.offer, name: join.name });
        }
      }
      return send(200, { ok: true, joins }, allowedOrigin);
    }

    /* Host: I'm done with this room. Without this a started game sits in the
       list until it expires, and anyone who clicks it knocks at a door nobody is
       listening behind any more. */
    if (request.method === "POST" && parts[2] === "close") {
      const room = rooms.get(word);
      if (!room) return send(200, { ok: true }, allowedOrigin);
      if (String(body.key || "") !== room.host) {
        return send(403, { error: "not your room" }, allowedOrigin);
      }
      rooms.delete(word);
      return send(200, { ok: true }, allowedOrigin);
    }

    /* Guest: knock, leaving an offer. Everything else is polling for the reply. */
    if (request.method === "POST" && parts[2] === "join") {
      const room = rooms.get(word);
      if (!room) {
        return send(404, { error: "nobody is hosting that room" }, allowedOrigin);
      }
      if (!looksLikeCode(body.offer)) {
        return send(400, { error: "bad offer" }, allowedOrigin);
      }
      /* Locked rooms. The attempt limiter is checked before the password so that
         a room under attack stops answering rather than getting slower, and the
         message is the same either way — a guesser learns nothing from it. */
      if (room.pass) {
        if (!passAllow(room)) {
          return send(429, { error: "too many tries — wait a minute" }, allowedOrigin);
        }
        if (!(await passOk(room, body.pass))) {
          room.fails.n++;
          return send(403, { error: "wrong password" }, allowedOrigin);
        }
        // Somebody who knows the password clears the count, so one person
        // fumbling it cannot shut their own friends out for the next minute.
        room.fails = null;
      }
      if (room.joins.size >= MAX_JOINS) {
        return send(503, { error: "that room is busy" }, allowedOrigin);
      }
      const id = newId();
      room.joins.set(id, {
        offer: body.offer, name: tidyName(body.name),
        answer: null, taken: false, at: Date.now()
      });
      return send(200, { ok: true, id, host: room.name }, allowedOrigin);
    }

    /* Host: here is the answer for that knock. */
    if (request.method === "POST" && parts[2] === "answer") {
      const room = rooms.get(word);
      if (!room) return send(404, { error: "gone" }, allowedOrigin);
      if (String(body.key || "") !== room.host) {
        return send(403, { error: "not your room" }, allowedOrigin);
      }
      const join = room.joins.get(String(body.id || ""));
      if (!join) return send(404, { error: "gone" }, allowedOrigin);
      if (!looksLikeCode(body.answer)) {
        return send(400, { error: "bad answer" }, allowedOrigin);
      }
      join.answer = body.answer;
      return send(200, { ok: true }, allowedOrigin);
    }

    /* Guest: is there a reply yet? Once taken, the join is finished with. */
    if (request.method === "GET" && parts[2] === "join" && parts[3]) {
      const room = rooms.get(word);
      if (!room) return send(404, { error: "gone" }, allowedOrigin);
      const join = room.joins.get(parts[3]);
      if (!join) return send(404, { error: "gone" }, allowedOrigin);
      if (!join.answer) return send(200, { waiting: true }, allowedOrigin);
      room.joins.delete(parts[3]);
      return send(200, { answer: join.answer }, allowedOrigin);
    }

    return send(404, { error: "no such thing" }, allowedOrigin);
  }

  return { handle, size: () => rooms.size };
}
