/* ══════════════════════════════════════════════════════════════════════
   The ladder.

   Twenty-one rungs from the smallest thing anyone has measured to the
   edge of what anyone can see. Every one of them carries a real number in
   metres, and the whole exhibit is built out of those numbers and nothing
   else: the rail, the camera, the spacing on screen, the calipers, the
   light-crossing times. There is no artistic "about this big" anywhere in
   the geometry.

   THE ORDER IS STRICTLY BY SIZE. That is worth saying out loud because it
   produces one result people argue with: the largest star we have measured
   is *smaller* than the planets' orbits, so Stephenson 2-18 lands between
   the Sun and Neptune. It is not a mistake. It is the point.

   Some rungs are objects and some are distances — the Moon's orbit, the
   gap to the nearest star. Those are labelled `dim: "across"` and the
   prose says what is being measured, because a distance quietly presented
   as an object is a lie by layout.

   `size`  the labelled measurement, in metres. This is the number.
   `dim`   what that number measures, in words.
   `alt`   the same measurement in whatever unit a person actually thinks
           in. Hand-written, never converted — "380 feet" is worth more
           than "1.16 × 10² m", and only a human knows which one lands.
   `box`   [width, height] as multiples of `size`. The labelled axis is
           always exactly 1; the other is the true proportion. This is what
           makes the caliper honest — it brackets the dimension the number
           is actually about.
   `tint`  the one colour the object collapses to when it is two pixels
           wide. Below that, an object is a dot, and the dot should be the
           right colour.
   ══════════════════════════════════════════════════════════════════════ */
window.LADDER = [
  {
    id: "electron",
    name: "An electron",
    kicker: "As small as it gets",
    size: 1e-18,
    dim: "at most, across",
    alt: "and every experiment says smaller",
    box: [1, 1],
    tint: "#bcd8ff",
    lede: "Nobody has ever measured how big an electron is, because as far as anyone can tell it does not have a size.",
    fact: "It is not small the way a grain of sand is small. Every experiment built to find an edge has come back empty, and the best of them can only say it is narrower than a millionth of a billionth of a billionth of a metre. Draw it any bigger than a smudge and you have made something up. So this is a smudge, drawn at that upper limit, with a dashed edge that means <em>we do not know where this stops</em>. There is nothing drawn inside it either, and that is not an omission: an electron has charge, spin and mass and no known parts. It is the one thing on this ladder with no interior to get wrong.",
    caveat: "The three empty decades to the right of this are real. There is nothing known between an electron and a proton.",
  },
  {
    id: "proton",
    name: "A proton",
    kicker: "The first real measurement",
    size: 1.68e-15,
    dim: "across, by charge radius",
    alt: "a millionth of a billionth of a metre",
    box: [1, 1],
    tint: "#ff8f6a",
    lede: "The first thing on this ladder anybody has actually put a number on — though the number is not an edge.",
    fact: "A proton is made of quarks, and the quarks are point-like too — so this width is not a shell around anything solid. It is the distance over which the charge is spread, and what is drawn here is that spread: electron scattering gives the proton a dipole form factor, which means the charge density falls off exponentially and <em>never stops</em>. The 0.84-femtometre radius is a root-mean-square, a moment of that curve rather than a boundary, which is why the ring marking it sits well outside the bright part. Physicists spent most of the 2010s arguing about its last two digits, because two ways of measuring it disagreed by more than either one's error bars. That fight is called the proton radius puzzle, and it is mostly settled now.",
    caveat: "No quarks are drawn inside this, on purpose. There are three of them, but a quark has no position you could mark and has never been observed on its own — three coloured dots orbiting inside a circle is the same fiction as an electron orbiting a nucleus like a planet.",
  },
  {
    id: "atom",
    name: "A hydrogen atom",
    kicker: "Mostly nothing",
    size: 1.06e-10,
    dim: "across",
    alt: "about one ten-billionth of a metre",
    box: [1, 1],
    tint: "#8fb7ff",
    lede: "One proton, one electron, and an enormous amount of empty space between them.",
    fact: "The atom is 63,000 times wider than the proton at the middle of it. Blow the proton up to the size of a marble and the electron is a third of a mile away, with nothing whatsoever in between. Every solid object you have ever touched is built out of this. The reason your hand does not go through a table is not that either one is full — it is that the electrons refuse to share.",
  },
  {
    id: "dna",
    name: "DNA",
    kicker: "The instructions",
    size: 2e-9,
    dim: "wide",
    alt: "two nanometres, or twenty atoms",
    box: [1, 3.2],
    tint: "#68d8c8",
    lede: "Twenty atoms wide, and about two metres long if you pulled one cell's worth straight.",
    fact: "Every cell in your body holds roughly two metres of this, wound tight enough to fit somewhere a thousand times smaller than the width of a hair. Stretched end to end, the DNA in one person would reach past the Sun and back — dozens of times over. It is the only object on this ladder that comes with a copy of the instructions for building the person looking at it.",
  },
  {
    id: "virus",
    name: "A virus",
    kicker: "Not quite alive",
    size: 1e-7,
    dim: "across",
    alt: "smaller than the wavelength of light",
    box: [1, 1],
    tint: "#9fb08a",
    lede: "A hundred nanometres of protein shell with instructions inside — too small to see with any light microscope.",
    fact: "Visible light has a wavelength of four hundred to seven hundred nanometres, which is several times wider than this. That is not a limitation of the microscope; it is a limitation of light. You cannot see a thing with a ruler coarser than the thing. Every image you have ever seen of a virus came from an electron beam, and the colours in it were chosen by a person.",
  },
  {
    id: "cell",
    name: "A red blood cell",
    kicker: "The smallest thing you are made of",
    size: 7.5e-6,
    dim: "across",
    alt: "a tenth the width of a hair",
    box: [1, 0.27],
    tint: "#c0392b",
    lede: "A dented disc, seven and a half microns wide, and there are about twenty-five trillion of them in you right now.",
    fact: "It is dished in the middle rather than round, which gives it more surface for its volume and lets it fold to squeeze through capillaries narrower than it is. It carries no nucleus and no DNA — it threw both away to make room for cargo. It will go around your body about 75,000 times over four months, and then it will be taken apart.",
  },
  {
    id: "you",
    name: "You",
    kicker: "Roughly the middle",
    size: 1.7,
    dim: "tall",
    alt: "five foot seven",
    box: [0.3, 1],
    tint: "#e8dcc8",
    lede: "You are about as many times bigger than a blood cell as the Sun is bigger than you.",
    fact: "This rung is not quite the middle of the ladder, but it is close, and the near-symmetry is real: there are eighteen decades of size below you and twenty-seven above. A human being is one of the few things in the universe positioned to notice both ends. Everything smaller than a blood cell you have only ever seen a picture of; everything bigger than the Moon's orbit, the same.",
  },
  {
    id: "elephant",
    name: "An African elephant",
    kicker: "The biggest thing that walks",
    size: 6.8,
    dim: "long",
    alt: "twenty-two feet, and eleven feet at the shoulder",
    box: [1, 0.47],
    tint: "#8d8a86",
    lede: "The largest land animal alive, and about four of you end to end.",
    fact: "A bull weighs six tonnes and can hear another elephant's call from six miles away, partly through its feet — the low end of the rumble travels through the ground as well as the air. Notice how little of a jump this is. Between you and the largest animal on land is less than one decade. Between you and the tree in the next frame is nearly two.",
  },
  {
    id: "tree",
    name: "Hyperion",
    kicker: "The tallest living thing",
    size: 116,
    dim: "tall",
    alt: "380 feet",
    box: [0.26, 1],
    tint: "#7a4a34",
    lede: "A coast redwood, measured at 116 metres, and the tallest known living thing on Earth.",
    fact: "It is taller than it should be able to be. Water is pulled to the top by the tension of the column itself, and somewhere near 120 metres that column starts to break — so the tree is within a few metres of the physical ceiling for its own plumbing. Its exact location is a secret, and the park closed the area to visitors in 2022 after too many people trampled the roots looking for it.",
  },
  {
    id: "lakes",
    name: "The Great Lakes",
    kicker: "A feature you can see from orbit",
    size: 1.25e6,
    dim: "end to end",
    alt: "780 miles",
    box: [1, 0.68],
    tint: "#3d7ea6",
    lede: "Superior alone is 563 kilometres long. All five together run about 1,250 kilometres from one end to the other.",
    fact: "They hold 22,700 cubic kilometres of water — roughly a fifth of all the fresh surface water on the planet, sitting in five holes gouged out by ice that left about eleven thousand years ago. Poured out evenly over the lower 48 states it would stand nearly three metres deep. This is the first rung you could pick out from space without being told where to look.",
  },
  {
    id: "earth",
    name: "The Earth",
    kicker: "Everything anyone has ever done",
    size: 1.2742e7,
    dim: "across",
    alt: "7,918 miles",
    box: [1, 1],
    tint: "#3f7fbf",
    lede: "Twelve thousand seven hundred and forty-two kilometres across, and the only rung on this ladder anybody has ever lived on.",
    fact: "It is smoother than a billiard ball. Everest and the Mariana Trench are both about nine kilometres off the mean, which on a globe this size is less than a tenth of a percent — a bump you could not feel with a fingertip. The whole of the atmosphere, all the weather there has ever been, is a film about as thick on this as the skin on an apple.",
  },
  {
    id: "moon",
    name: "The Moon's orbit",
    kicker: "The far edge of where we have been",
    size: 7.688e8,
    dim: "across",
    alt: "477,700 miles",
    box: [1, 1],
    tint: "#8b8f9a",
    lede: "A distance, not an object: the full width of the Moon's path around the Earth.",
    fact: "Every other planet in the solar system fits inside the gap between the Earth and the Moon, side by side, with room left over — Mercury, Venus, Mars, Jupiter, Saturn, Uranus and Neptune add up to about 380,000 kilometres, and the gap is 384,400. Twenty-four people have crossed it. Nobody has been past this line since December 1972.",
  },
  {
    id: "sun",
    name: "The Sun",
    kicker: "Where the light comes from",
    size: 1.3914e9,
    dim: "across",
    alt: "865,000 miles",
    box: [1, 1],
    tint: "#ffc861",
    lede: "One hundred and nine Earths across, and 333,000 times their mass.",
    fact: "It is a completely ordinary star — smaller than most of the ones you can pick out by eye at night, because the ones you can pick out by eye are the show-offs. It holds 99.86 percent of all the mass in the solar system. Everything else on the next several rungs, every planet and moon and comet, is built out of what was left over.",
  },
  {
    id: "stephenson",
    name: "Stephenson 2-18",
    kicker: "The largest star we have measured",
    size: 2.99e12,
    dim: "across",
    alt: "twenty times the Earth's distance from the Sun",
    box: [1, 1],
    tint: "#d9553f",
    lede: "Two thousand one hundred and fifty times the width of the Sun. Ten billion Suns would fit inside it.",
    fact: "Put it where the Sun is and its surface would swallow Mercury, Venus, Earth, Mars, Jupiter, and reach out past the orbit of Saturn. It is not dense — a red hypergiant this size is thinner than the air in this room over most of its volume; it is a vast glowing atmosphere around a small heavy core, and it is falling apart.",
    caveat: "The size depends on the star belonging to the Stephenson 2 cluster, which is disputed. If it is a nearer foreground star it could be several times smaller. This is the biggest number with a serious paper behind it, not a settled fact.",
  },
  {
    id: "solar",
    name: "The solar system",
    kicker: "A star is smaller than its planets' orbits",
    size: 8.99e12,
    dim: "across",
    alt: "sixty times the Earth's distance from the Sun",
    box: [1, 1],
    tint: "#5f7d9e",
    lede: "Neptune's orbit, end to end — nine billion kilometres, and only three times wider than the star in the last frame.",
    fact: "Sunlight takes four hours and ten minutes to reach Neptune. The Sun itself, at this scale, is smaller than one pixel on your screen, and the planets are far smaller than that — which is the honest picture. Every diagram of the solar system you have ever seen cheated on the spacing, because the true version is a few specks of dust in an enormous amount of nothing.",
  },
  {
    id: "oort",
    name: "The Oort Cloud",
    kicker: "Where the comets come from",
    size: 2.99e16,
    dim: "across",
    alt: "a hundred thousand times the Earth's distance from the Sun",
    box: [1, 1],
    tint: "#7e8ba6",
    lede: "A shell of frozen debris wrapped around the Sun, reaching out to something like 100,000 times the Earth's distance from it.",
    fact: "Nobody has ever seen it. It is inferred from the long-period comets that fall in from every direction with orbits that all seem to turn around at about the same enormous distance, which is what a shell would look like from the inside. It is three thousand times wider than the frame you were just looking at, and it is still, technically, the Sun's.",
  },
  {
    id: "proxima",
    name: "The nearest star",
    kicker: "And the Oort Cloud nearly touches it",
    size: 4.018e16,
    dim: "away",
    alt: "forty trillion kilometres",
    box: [1, 0.14],
    tint: "#e05a4a",
    lede: "Proxima Centauri, 4.25 light-years off — and look how little bigger that is than the frame before it.",
    fact: "This is the closest another star ever gets, and the Sun's own cloud of comets reaches most of the way there. There is no real gap between one star's territory and the next; they overlap. Voyager 1, the furthest thing we have ever thrown, has been going for forty-eight years and has covered about a five-hundredth of this line.",
  },
  {
    id: "galaxy",
    name: "The Milky Way",
    kicker: "One of a few hundred billion",
    size: 9.461e20,
    dim: "across",
    alt: "588 quadrillion miles, which is why nobody uses miles",
    box: [1, 0.45],
    tint: "#cbb489",
    lede: "A hundred thousand light-years of stars, and the last frame — the whole distance to the nearest one — is a two-thousandth of it.",
    fact: "There are somewhere between one and four hundred billion stars in it, and the Sun is thirty thousand light-years out from the middle, in a minor spur off one of the arms. It takes about 230 million years to go around once. The last time the Sun was where it is now, the dinosaurs had not started yet.",
  },
  {
    id: "localgroup",
    name: "The Local Group",
    kicker: "Our galaxy's neighbours",
    size: 9.461e22,
    dim: "across",
    alt: "a hundred Milky Ways end to end",
    box: [1, 0.75],
    tint: "#9aa6c4",
    lede: "About eighty galaxies, held together by their own gravity — but really just two big ones and a crowd of dwarfs.",
    fact: "The Milky Way and Andromeda are most of the mass here, and they are falling toward each other at 110 kilometres a second. They will collide in about four and a half billion years. Almost nothing will hit anything — the stars are so far apart that the two galaxies will pass through each other like two clouds of gnats — but the shapes will not survive it.",
  },
  {
    id: "laniakea",
    name: "Laniakea",
    kicker: "The supercluster we are falling through",
    size: 4.92e24,
    dim: "across",
    alt: "five thousand Milky Ways end to end",
    box: [1, 0.8],
    tint: "#7f6fa8",
    lede: "A hundred thousand galaxies, defined in 2014 not by where they are but by which way they are moving.",
    fact: "The boundary is drawn where the flow changes direction: everything inside is drifting toward the same place, a gravitational low called the Great Attractor, and everything outside is drifting somewhere else. It is less a structure than a watershed. The name is Hawaiian for immeasurable heaven.",
  },
  {
    id: "universe",
    name: "The observable universe",
    kicker: "The edge of what can be seen",
    size: 8.8e26,
    dim: "across",
    alt: "and the universe is only 13.8 billion years old",
    box: [1, 1],
    tint: "#6d7fb0",
    lede: "Ninety-three billion light-years across — not because the universe is that old, but because space has been stretching the whole time the light was in flight.",
    fact: "The universe is 13.8 billion years old, so the natural guess is that we can see 27.6 billion light-years across. But the space those photons crossed kept expanding while they crossed it, and the things that emitted them are now much further away than they were. This is the whole of it: everything anyone will ever be able to look at. Whether there is more beyond it is not a question anybody can answer by looking. <em>There is no photograph of this frame and there cannot be one</em> — nobody has ever been outside it, and it has no outside. What is drawn is a composite of the kind the real visualizations are: galaxies reddening with distance because distance here is lookback time, filaments in the proportions the redshift surveys find, and at the rim <em>the actual thing</em> — WMAP's nine-year map of the cosmic microwave background, the oldest light there is, unwrapped from the ellipse it is usually printed as and laid back onto the shell it came off. Every other rung on this ladder grew out of the lumps in it.",
    caveat: "This is not the size of the universe. It is the size of the part close enough for light to have reached us. The universe itself may be far larger, and may be infinite. The frame is a visualization assembled from observations, not an image of the thing — there is no vantage outside this to photograph it from. The shell is real measured data (NASA / WMAP Science Team); the galaxies and filaments inside it are drawn from a seed rather than from a catalogue, and their reddening with distance is the only other physics in the picture.",
  },
];
