#!/usr/bin/env python3
"""
build-stars.py — turn the Yale Bright Star Catalogue into the exhibit's sky.

Input:  _project-originals/bsc5.dat  (BSC5, 9110 entries, gitignored originals)
Output: data/stars.js                (committed — the page reads this)

The exhibit stores no colour. Per the blueprint (§8.2) a star is three physical
quantities and nothing else:

    unit direction (x, y, z)   from RA/Dec, J2000
    apparent magnitude V       -> bolometric-ish visual flux at load time
    colour index B-V           -> effective temperature at load time

Flux and temperature are derived in the page (colour.js / sky.js) rather than
here, so the data file stays auditable: every number in it comes straight off
the catalogue.

Run:  python3 projects/how-speed-affects-time/build-stars.py
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(REPO, "_project-originals", "bsc5.dat")
OUT = os.path.join(HERE, "data", "stars.js")

# BSC5 fixed-width columns (1-indexed, per the ADC readme)
COL = {
    "hr":    (1, 4),
    "name":  (5, 14),
    "rah":   (76, 77),
    "ram":   (78, 79),
    "ras":   (80, 83),
    "design": (84, 84),
    "ded":   (85, 86),
    "dem":   (87, 88),
    "des":   (89, 90),
    "vmag":  (103, 107),
    "bv":    (110, 114),
    "sp":    (128, 147),
}


def field(line, key):
    a, b = COL[key]
    return line[a - 1:b]


def main():
    if not os.path.exists(SRC):
        sys.exit("missing %s — the BSC5 original is not in this checkout" % SRC)

    stars = []
    no_bv = 0
    skipped = 0

    with open(SRC, "r", encoding="latin-1") as fh:
        for line in fh:
            try:
                rah = float(field(line, "rah"))
                ram = float(field(line, "ram"))
                ras = float(field(line, "ras"))
                ded = float(field(line, "ded"))
                dem = float(field(line, "dem"))
                des = float(field(line, "des"))
                v = float(field(line, "vmag"))
            except ValueError:
                # novae, clusters and a handful of deleted entries carry no
                # position or no magnitude. They are not stars you can see.
                skipped += 1
                continue

            sign = -1.0 if field(line, "design").strip() == "-" else 1.0

            try:
                bv = float(field(line, "bv"))
            except ValueError:
                # No measured colour. Rather than invent one, fall back to the
                # catalogue's median (B-V = 0.51, an early-G star) and count it.
                bv = 0.51
                no_bv += 1

            import math
            ra = math.radians((rah + ram / 60.0 + ras / 3600.0) * 15.0)
            dec = sign * math.radians(ded + dem / 60.0 + des / 3600.0)

            cd = math.cos(dec)
            x = cd * math.cos(ra)
            y = cd * math.sin(ra)
            z = math.sin(dec)

            stars.append((x, y, z, v, bv))

    # Brightest first. The renderer draws glare halos for the leading slice
    # only, so a sorted file lets it take a prefix instead of a search.
    stars.sort(key=lambda s: s[3])

    faintest = max(s[3] for s in stars)
    brightest = min(s[3] for s in stars)

    nums = []
    for x, y, z, v, bv in stars:
        nums.append("%.6f,%.6f,%.6f,%.2f,%.3f" % (x, y, z, v, bv))

    body = ",\n".join(nums[i] for i in range(len(nums)))

    header = """/* ══════════════════════════════════════════════════════════════════════
   stars.js — the actual sky. Generated by build-stars.py; do not hand-edit.

   Source: Yale Bright Star Catalogue, 5th revised edition (Hoffleit & Warren
   1991), J2000 positions. %d entries in, %d stars out — the rest are
   novae, clusters and deleted entries with no position or no magnitude.

   Five numbers per star, flat, in one array:

       x, y, z    unit direction in equatorial J2000 coordinates
       V          apparent visual magnitude   (%.2f to %.2f)
       B-V        colour index                (%d stars had none; see script)

   No colour, no brightness, no size. Those are physics, and the page does
   them at load: V becomes a flux in lux, B-V becomes a temperature in
   kelvin (Ballesteros 2012), and everything after that is the transform.

   Sorted brightest-first so the renderer can take a prefix.
   ══════════════════════════════════════════════════════════════════════ */
window.HSAT_STARS = new Float32Array([
""" % (9110, len(stars), brightest, faintest, no_bv)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(header)
        fh.write(body)
        fh.write("\n]);\nwindow.HSAT_STARS_STRIDE = 5;\n")

    size = os.path.getsize(OUT)
    print("wrote %s" % os.path.relpath(OUT, REPO))
    print("  %d stars, V %.2f to %.2f, %d without B-V, %d entries skipped"
          % (len(stars), brightest, faintest, no_bv, skipped))
    print("  %.0f KB" % (size / 1024.0))


if __name__ == "__main__":
    main()
