#!/usr/bin/env python3
"""Build Victoria's open website: her index.html, with Ric's extras riding inside it.

    python3 scripts/build-open-site.py ~/Downloads/hermesco-deploy.zip
    python3 scripts/build-open-site.py path/to/her/index.html [--out DIR] [--demo]

The result is ONE index.html she uploads in place of her own. It is her file — her screens,
her styles, her code, still one <style> and one inline <script> — with three changes:

  1. The top of her script (above the STATE line, where her database section lives) is
     Ric's database connection instead: the same project and key she already publishes,
     plus the offline queue. No sign-in — open the page and pick your name, as today. No
     demo. Her built-in copy of the race data is not carried over.
  2. Two lines in her code: start-up waits for Ric's layer (a no-op for everyone but Ric and
     Sydney), and the crew sheet says "18hr pace".
  3. Blocks marked data-ric at the end of <head> and <body>: Ric's Notes screen for
     everyone (shared/notes-layer.js + notes.css — Victoria asked for it), and Ric's
     race-day layer (shared/ric-layer.js + styles.css), which Ric and Sydney switch on from
     Settings ("Ric's race-day version"); it starts off, on Victoria's version.

When she edits the file and sends it back, scripts/import-original.py takes it as usual:
it drops everything above STATE and every data-ric block, so only her part is imported.

The output holds the real database key, so it is written OUTSIDE this repo (default
~/Desktop/HERMISCUS for Victoria/). --demo builds a keyless copy on the made-up race, for
testing without touching the live data.
"""
import json
import pathlib
import re
import sys
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
SHARED = ROOT / 'shared'
STATE = '/* ================= STATE ================= */'


def read_source(path):
    path = pathlib.Path(path).expanduser()
    if path.suffix == '.zip':
        with zipfile.ZipFile(path) as z:
            return z.read('index.html').decode('utf-8')
    return path.read_text(encoding='utf-8')


def strip_ric_blocks(html):
    """Remove the data-ric blocks a previous build put in, so a returned file rebuilds cleanly."""
    return re.sub(r'\s*<(style|script)\b[^>]*\bdata-ric(?=[\s>])[^>]*>.*?</\1>', '', html, flags=re.S)


def replace_once(text, old, new, what):
    if text.count(old) != 1:
        sys.exit(f'build-open-site: expected one {what}, found {text.count(old)}. Her file changed here.')
    return text.replace(old, new)


def real_config():
    local = (SHARED / 'config.local.js').read_text(encoding='utf-8')
    url = re.search(r"supabaseUrl:\s*'([^']+)'", local)
    key = re.search(r"publishableKey:\s*'([^']+)'", local)
    if not url or not key:
        sys.exit('build-open-site: shared/config.local.js has no database address/key.')
    if key.group(1).startswith('sb_secret') or '"role":"service_role"' in key.group(1):
        sys.exit('build-open-site: that is not a browser key. Refusing.')
    return url.group(1), key.group(1)


def main():
    args = sys.argv[1:]
    demo = '--demo' in args
    out = pathlib.Path('~/Desktop/HERMISCUS for Victoria').expanduser()
    if '--out' in args:
        out = pathlib.Path(args[args.index('--out') + 1]).expanduser()
    sources = [a for i, a in enumerate(args) if not a.startswith('--') and (i == 0 or args[i - 1] != '--out')]
    if len(sources) != 1:
        sys.exit(__doc__)
    if out.resolve().is_relative_to(ROOT.parent.parent) and not demo:
        sys.exit('build-open-site: the output holds the real key; write it outside the website repo.')

    html = strip_ric_blocks(read_source(sources[0]))
    if len(re.findall(r'<style[^>]*>', html)) != 1 or html.count(STATE) != 1:
        sys.exit('build-open-site: expected her file — one <style> and the STATE line.')

    # ---- 1. her script's top: Ric's connection instead of her database section
    script_open = html.rindex('<script>', 0, html.index(STATE)) + len('<script>')
    config = "{ accountDomain: 'hermiscus.local' }" if demo else json.dumps(
        dict(zip(('supabaseUrl', 'publishableKey'), real_config())) | {'accountDomain': 'hermiscus.local'})
    connection = f"""
/* ================= RIC'S DATABASE CONNECTION =================
   Generated by Ric's build script (scripts/build-open-site.py in his website repo).
   Everything from here down to the STATE line is replaced on every build, so don't edit
   it — put app code below STATE. It is the same database and key this page always used,
   plus the offline queue Ric's screens rely on. */
window.HERMISCUS_CONFIG = Object.freeze({config});
// Open page, no sign-in: requests go out with the page's own public key.
window.HermiscusAuth = Object.freeze({{
  demo: {'true' if demo else 'false'},
  readSession(){{ const k = window.HERMISCUS_CONFIG.publishableKey; return k ? {{access_token:k}} : null; }},
  async authorizedHeaders(headers = {{}}){{
    const k = window.HERMISCUS_CONFIG.publishableKey || '';
    return {{...headers, apikey:k, Authorization:'Bearer '+k}};
  }},
  profileName(){{ try{{ return (JSON.parse(localStorage.getItem('hermesco_me')||'null')||{{}}).name||''; }}catch(_){{ return ''; }} }},
  clearPrivateState(){{}},
}});
// Start-up waits for Ric's blocks (Notes for everyone; his race-day layer for Ric and Sydney
// when they have switched it on in Settings).
(() => {{
  const who = window.HermiscusAuth.profileName().toLowerCase();
  let on = false;
  try {{ on = localStorage.getItem('hermiscus_use_ric_' + who) === '1'; }} catch (_) {{}}
  window.HERMISCUS_LAYER = ['ric', 'sydney'].includes(who) && on;
  window.HermiscusBeforeStart = new Promise(resolve => {{ window.HermiscusRelease = resolve; }});
  if (window.HERMISCUS_LAYER) {{
    const sheet = document.getElementById('ric-style');
    if (sheet) sheet.media = 'all';
  }}
}})();
""" + ((SHARED / 'demo-data.js').read_text(encoding='utf-8') if demo else '') + '\n' \
        + (SHARED / 'ric-dashboard-logic.js').read_text(encoding='utf-8') + '\n' \
        + (SHARED / 'data.js').read_text(encoding='utf-8') + '\n'
    html = html[:script_open] + connection + html[html.index(STATE):]

    # ---- 2. two lines in her code
    gate = "  // Ric's layer (Ric and Sydney only) loads after this file; wait for it before drawing.\n" \
           "  if(window.HermiscusBeforeStart) await window.HermiscusBeforeStart;\n"
    if 'await window.HermiscusBeforeStart' not in html:
        html = replace_once(html, "  if(ME){ await showApp(); }", gate + "  if(ME){ await showApp(); }", 'start-up line')
    html = html.replace("bits.push(`plan for this leg: ${fmtPace(planPace)}`);",
                        "bits.push(`${CONFIG.goal_finish_hours||18}hr pace: ${fmtPace(planPace)}`);")

    # ---- 3. Ric's blocks
    ric_css = (SHARED / 'styles.css').read_text(encoding='utf-8')
    notes_css = (SHARED / 'notes.css').read_text(encoding='utf-8')
    head_block = f'<style data-ric id="notes-style">\n/* Ric\'s Notes screen — for everyone. Generated; don\'t edit. */\n{notes_css}</style>\n'
    head_block += f'<style data-ric id="ric-style" media="not all">\n/* Ric\'s stylesheet — on for Ric and Sydney only. Generated; don\'t edit. */\n{ric_css}</style>\n'
    html = replace_once(html, '</head>', head_block + '</head>', '</head>')
    layer = (SHARED / 'ric-layer.js').read_text(encoding='utf-8')
    notes = (SHARED / 'notes-layer.js').read_text(encoding='utf-8')
    if re.search(r'</script|<!--|<script', layer + notes, re.I):
        sys.exit('build-open-site: a layer contains text that would break the page.')
    loader = """<script type="text/plain" data-ric id="notes-layer-src">
""" + notes + """</script>
<script type="text/plain" data-ric id="ric-layer-src">
""" + layer + """</script>
<script data-ric>
/* Ric's extras — generated by his build script; don't edit. They switch on only for Ric and
   Sydney, on top of Victoria's app. */
(() => {
  const people = ['ric', 'sydney'];
  const layerFor = name => {
    const who = String(name || '').toLowerCase();
    let on = false;
    try { on = localStorage.getItem('hermiscus_use_ric_' + who) === '1'; } catch (_) {}
    return people.includes(who) && on;
  };
  // Picking Ric or Sydney (or leaving them) reloads, so the page is set up for exactly that
  // person: their Settings switch, and the race-day layer if they have it on.
  const loadedAs = window.HermiscusAuth.profileName().toLowerCase();
  const herEnterAs = window.enterAs;
  window.enterAs = function (p) {
    const next = String(p && p.name || '').toLowerCase();
    if (next !== loadedAs && (people.includes(next) || people.includes(loadedAs) || layerFor(next) !== !!window.HERMISCUS_LAYER)) {
      localStorage.setItem('hermesco_me', JSON.stringify({id:p.id, name:p.name, role:p.role, color:p.color, color2:p.color2}));
      location.reload();
      return;
    }
    return herEnterAs(p);
  };
  // Offline saves go out when the signal comes back.
  window.addEventListener('online', async () => { if (await flushOfflineQueue()) await loadAppData(); });
  setInterval(() => { if (ME && getOfflineQueue().length && navigator.onLine) flushOfflineQueue({quiet:true}); }, 15000);

  // "Ric's race-day version" in Settings, for Ric and Sydney.
  const who = window.HermiscusAuth.profileName().toLowerCase();
  const settings = document.getElementById('page-settings');
  const addChoice = () => {
    if (!people.includes(who) || !settings) return;
    const key = 'hermiscus_use_ric_' + who;
    const title = document.createElement('div');
    title.className = 'sec-title';
    title.style.marginTop = '22px';
    title.textContent = 'App version';
    const box = document.createElement('label');
    box.className = 'card';
    box.style.cssText = 'display:flex;align-items:center;gap:12px;min-height:44px;cursor:pointer';
    box.innerHTML = '<input type="checkbox" style="width:22px;height:22px;margin:0;flex:none">' +
      "<span><b>Ric's race-day version</b><br><small>Overview, Crew Stop, Pace Dad and Prep, on top of Victoria's app.</small></span>";
    const check = box.querySelector('input');
    check.checked = !!window.HERMISCUS_LAYER;
    check.addEventListener('change', () => {
      try { check.checked ? localStorage.setItem(key, '1') : localStorage.removeItem(key); } catch (_) {}
      location.reload();
    });
    const hint = document.createElement('div');
    hint.className = 'save-hint';
    hint.textContent = "Remembered on this device. Untick for Victoria's version.";
    settings.append(title, box, hint);
  };
  const run = id => {
    const script = document.createElement('script');
    script.textContent = document.getElementById(id).textContent + '\\n//# sourceURL=' + id.replace('-src', '') + '.js';
    document.body.appendChild(script);
  };
  window.HERMISCUS_HER = Object.freeze({ goPage: window.goPage, loadAppData: window.loadAppData, liveSyncTick: window.liveSyncTick });
  run('notes-layer-src');                      // Ric's Notes: everyone
  if (window.HERMISCUS_LAYER) run('ric-layer-src');
  addChoice();
  window.HermiscusRelease();
})();
</script>
"""
    html = replace_once(html, '</body>', loader + '</body>', '</body>')

    out.mkdir(parents=True, exist_ok=True)
    (out / 'index.html').write_text(html, encoding='utf-8')
    for doc in ('AGENTS.md',):
        (out / doc).write_text((ROOT / doc).read_text(encoding='utf-8'), encoding='utf-8')
    (out / 'CLAUDE.md').write_text((ROOT / 'AGENTS.md').read_text(encoding='utf-8'), encoding='utf-8')
    print(f"build-open-site: wrote {out / 'index.html'}{' (DEMO, no key)' if demo else ''}")


if __name__ == '__main__':
    main()
