#!/bin/bash
# Daily Apex sync, run by launchd (see apex-sync.plist).
#
# Takes one snapshot through the tracker keyhole and regenerates apex-data.js.
# It will commit that file on its own, but only when it is the single thing that
# changed and the repo is on main — anything else and it leaves the working tree
# exactly as it found it and says so in the log. It never pushes: on this repo a
# push is a publish, and that stays Ric's call.
#
# The snapshot is the whole point of running daily. Apex keeps no match history,
# so the site's slope is built out of one reading per day; a day missed is a day
# the graph cannot get back.
#
# Log: ~/Library/Logs/apex-sync.log

set -uo pipefail

REPO="/Users/ricmassey/RicsWebsite"
DATA="projects/apex/apex-data.js"
LOG="$HOME/Library/Logs/apex-sync.log"

mkdir -p "$(dirname "$LOG")"
exec >>"$LOG" 2>&1
echo ""
echo "───────────── $(date '+%Y-%m-%d %H:%M:%S') ─────────────"

cd "$REPO" || { echo "no repo at $REPO"; exit 1; }

python3 projects/apex/pull-apex.py
status=$?

# Exit 2 is a missing gamertag or Keychain key. Retrying changes nothing, and
# neither does waiting, so say what is missing and stop.
if [ $status -eq 2 ]; then
  echo "misconfigured — the message above needs sorting out by hand"
  exit $status
fi

# Exit 1 is the API being unreachable or unhappy: a rate limit, a bad gateway,
# ALS being mid-deploy. One retry after a pause covers nearly all of it, and the
# next daily run covers the rest.
if [ $status -ne 0 ]; then
  echo "pull failed (exit $status) — retrying once in 60s"
  sleep 60
  python3 projects/apex/pull-apex.py
  status=$?
fi

if [ $status -ne 0 ]; then
  echo "pull still failing (exit $status) — leaving everything alone"
  exit $status
fi

if git diff --quiet -- "$DATA"; then
  echo "nothing moved since the last read"
  exit 0
fi

branch=$(git rev-parse --abbrev-ref HEAD)
dirty=$(git status --porcelain | grep -v " $DATA\$" | grep -v "^?? " || true)

if [ "$branch" != "main" ]; then
  echo "new Apex data, but on branch '$branch' — left uncommitted for Ric"
  exit 0
fi
if [ -n "$dirty" ]; then
  echo "new Apex data, but other files are modified — left uncommitted:"
  echo "$dirty"
  exit 0
fi

git add "$DATA"
git commit -q -m "APEX: today's read through the keyhole

Generated by pull-apex.py on the daily timer. Not pushed — publishing
is still a deliberate act." && echo "committed $(git rev-parse --short HEAD) (not pushed)"

echo "run 'git push' when you want it live"
exit 0
