// Generated by pull-apex.py — do not edit by hand, except the `manual` block.
//
// Apex exposes almost nothing about a player: only the three stat trackers
// equipped on the banner of the legend being played. Everything here is either
// read through that keyhole (source "api") or typed in from the in-game career
// panel, which no API exposes (source "manual"). pull-apex.py preserves the
// manual block on every run.
window.APEX_DATA = {
 "generated": "2026-07-30T00:00:00Z",
 "source": "seed",
 "live": false,
 "account": {
  "name": "RicGoneCrazy",
  "uid": null,
  "platform": "X1",
  "level": null,
  "prestige": null,
  "toNextLevelPercent": null
 },
 "status": {
  "online": false,
  "inGame": false,
  "text": null,
  "selectedLegend": null,
  "checked": null
 },
 "rank": {
  "name": null,
  "div": null,
  "score": null,
  "ladderPos": null
 },
 "legends": {
  "Alter": {
   "trackers": [
    {
     "key": "kills",
     "name": "Kills",
     "value": 3500,
     "source": "manual",
     "asOf": "2026-07-30",
     "approx": true
    }
   ],
   "equipped": true,
   "lastSeen": "2026-07-30"
  }
 },
 "career": {
  "kills": null,
  "wins": null,
  "games": null,
  "kd": null,
  "bestKills": null,
  "asOf": null,
  "source": "manual"
 },
 "history": []
};
