// Generated by pull-apex.py — do not edit by hand, except the `manual` block.
//
// Apex exposes almost nothing about a player: only the three stat trackers
// equipped on the banner of the legend being played. Everything here is either
// read through that keyhole (source "api") or typed in from the in-game career
// panel, which no API exposes (source "manual"). pull-apex.py preserves the
// manual block on every run.
window.APEX_DATA = {
 "generated": "2026-08-20T04:06:17Z",
 "source": "pull-apex.py",
 "live": true,
 "account": {
  "name": "RicGoneCrazy",
  "uid": "2535464424730600",
  "platform": "X1",
  "level": 117,
  "prestige": 2,
  "toNextLevelPercent": 34
 },
 "status": {
  "online": true,
  "inGame": false,
  "text": "In lobby",
  "selectedLegend": "Caustic",
  "checked": "2026-08-20T04:06:17Z"
 },
 "rank": {
  "name": "Platinum",
  "div": 3,
  "score": 9423,
  "ladderPos": null
 },
 "legends": {
  "Alter": {
   "trackers": [
    {
     "key": "damage",
     "name": "BR Damage",
     "value": 740675,
     "source": "api",
     "asOf": "2026-08-20"
    },
    {
     "key": "kills",
     "name": "BR Kills",
     "value": 1272,
     "source": "api",
     "asOf": "2026-08-20"
    }
   ],
   "equipped": true,
   "lastSeen": "2026-08-20"
  },
  "Gibraltar": {
   "trackers": [
    {
     "key": "damage",
     "name": "BR Damage",
     "value": 175287,
     "source": "api",
     "asOf": "2026-08-20"
    },
    {
     "key": "kills",
     "name": "BR Kills",
     "value": 464,
     "source": "api",
     "asOf": "2026-08-20"
    },
    {
     "key": "wins",
     "name": "BR Wins",
     "value": 31,
     "source": "api",
     "asOf": "2026-08-20"
    }
   ],
   "lastSeen": "2026-08-20",
   "equipped": true
  },
  "Caustic": {
   "trackers": [
    {
     "key": "kills",
     "name": "BR Kills",
     "value": 91,
     "source": "api",
     "asOf": "2026-08-20"
    },
    {
     "key": "wins",
     "name": "BR Wins",
     "value": 1,
     "source": "api",
     "asOf": "2026-08-20"
    }
   ],
   "lastSeen": "2026-08-20",
   "equipped": true
  },
  "Axle": {
   "trackers": [
    {
     "key": "damage",
     "name": "BR Damage",
     "value": 236041,
     "source": "api",
     "asOf": "2026-08-20"
    },
    {
     "key": "kills",
     "name": "BR Kills",
     "value": 570,
     "source": "api",
     "asOf": "2026-08-20"
    }
   ],
   "lastSeen": "2026-08-20",
   "equipped": true
  }
 },
 "career": {
  "kills": 3500,
  "wins": null,
  "games": null,
  "kd": null,
  "bestKills": null,
  "asOf": "2026-07-30",
  "source": "manual",
  "approx": true
 },
 "history": [
  {
   "d": "2026-08-20",
   "trackedKills": 2397,
   "careerKills": 3500,
   "rp": 9423,
   "level": 117
  }
 ]
};
