#!/usr/bin/env python3
"""Pull Ric's Apex Legends numbers into apex-data.js.

Apex has no official API and no match log. Every stats site reads the same
keyhole: the three trackers equipped on the banner of the legend you are
currently playing. So this script does not fetch a history — it takes a
snapshot, and keeps its own.

What that means in practice:

  * A legend only appears once it has been seen with trackers equipped.
  * Tracker values are cumulative counters, so a value never goes down. If a
    read comes back lower than what we already had, we keep the higher one —
    that is a stale cache upstream, not lost kills.
  * Career kills/wins are account-wide, but the only place they are shown is
    the in-game career panel (lobby → gamertag), which no API exposes. Those
    live in the `career` block and are typed in by hand; this script never
    overwrites them.
  * One history point per day, so the page can draw a slope instead of a total.

Stdlib only — the site has no build step and no dependencies.

Usage:
    python3 projects/apex/pull-apex.py

Exit codes: 0 synced, 1 the pull failed, 2 misconfigured (a gamertag or the
Keychain key is missing — retrying will not help).
"""

from __future__ import annotations

import json
import os
import re
import ssl
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import date, datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
ACCOUNT = HERE / "apex-account.json"
OUT = HERE / "apex-data.js"

API = "https://api.apexlegendsstatus.com"

# The API key is a secret, so it lives in the Keychain, never in the repo.
# Store it with:
#   security add-generic-password -s apex-als -a <gamertag> -w
KEYCHAIN_SERVICE = "apex-als"

# Free keys are limited to a few requests a second. We make one or two a day.
TIMEOUT = 20

HEADER = """\
// Generated by pull-apex.py — do not edit by hand, except the `manual` block.
//
// Apex exposes almost nothing about a player: only the three stat trackers
// equipped on the banner of the legend being played. Everything here is either
// read through that keyhole (source "api") or typed in from the in-game career
// panel, which no API exposes (source "manual"). pull-apex.py preserves the
// manual block on every run.
window.APEX_DATA = """


class Failed(Exception):
    """The pull broke. Worth a retry later."""


class Misconfigured(Exception):
    """Something is missing that a retry will not fix."""


# ── credentials ────────────────────────────────────────────────────────────


def read_account() -> dict:
    if not ACCOUNT.exists():
        raise Misconfigured(
            f"no {ACCOUNT.name}. Copy the example and fill in the gamertag:\n"
            f"    cp {ACCOUNT.with_suffix('.example.json').name} {ACCOUNT.name}"
        )
    try:
        account = json.loads(ACCOUNT.read_text())
    except json.JSONDecodeError as exc:
        raise Misconfigured(f"{ACCOUNT.name} is not valid JSON: {exc}") from exc
    if not account.get("gamertag"):
        raise Misconfigured(f"{ACCOUNT.name} has no gamertag")
    account.setdefault("platform", "X1")
    return account


def api_key(gamertag: str) -> str:
    """Fetch the ALS API key from the Keychain. Never printed, never stored."""
    store = (
        f"    security add-generic-password -s {KEYCHAIN_SERVICE} -a {gamertag} -U -w\n"
        f"Run that in Terminal.app — the -w prompt needs a real terminal. Launched\n"
        f"without one it stores an EMPTY password and still reports success."
    )
    found = subprocess.run(
        ["security", "find-generic-password", "-s", KEYCHAIN_SERVICE, "-a", gamertag, "-w"],
        capture_output=True,
        text=True,
    )
    if found.returncode != 0:
        raise Misconfigured(
            f"no Keychain entry for {gamertag}. Get a free key at "
            f"https://apexlegendsapi.com, then:\n{store}"
        )
    key = found.stdout.strip()
    if not key:
        raise Misconfigured(
            f"the Keychain entry for {gamertag} is empty. That happens when the add\n"
            f"command ran without an interactive terminal. Store it again:\n{store}"
        )
    return key


def scrub(text: str, secret: str) -> str:
    """Never let the key reach the terminal, however it got into the output."""
    if secret and text:
        return text.replace(secret, "********")
    return text


# ── the API ────────────────────────────────────────────────────────────────


def ssl_context() -> ssl.SSLContext:
    """A verifying TLS context that works on a Mac with no configured trust store.

    The python.org framework builds ship without CA certificates unless someone
    runs "Install Certificates.command", so ssl.create_default_context() has
    nothing to verify against and every HTTPS call dies with
    CERTIFICATE_VERIFY_FAILED. Fall back to a real bundle rather than doing the
    thing every StackOverflow answer suggests and turning verification off.
    """
    default = ssl.create_default_context()
    paths = ssl.get_default_verify_paths()
    if paths.cafile or paths.capath:
        return default

    try:
        import certifi
        return ssl.create_default_context(cafile=certifi.where())
    except Exception:
        pass

    system_bundle = "/etc/ssl/cert.pem"  # present on every macOS
    if os.path.exists(system_bundle):
        return ssl.create_default_context(cafile=system_bundle)

    raise Failed(
        "no CA certificates available to verify HTTPS. On a python.org build, run\n"
        "    /Applications/Python 3.12/Install Certificates.command"
    )


def get(path: str, key: str, **params) -> dict:
    params["auth"] = key
    url = f"{API}/{path}?" + urllib.parse.urlencode(params)
    request = urllib.request.Request(url, headers={"User-Agent": "rics-website-apex-sync"})
    try:
        with urllib.request.urlopen(request, timeout=TIMEOUT, context=ssl_context()) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        raise Failed(f"{path} returned HTTP {exc.code}") from exc
    except urllib.error.URLError as exc:
        raise Failed(f"could not reach {API}: {scrub(str(exc.reason), key)}") from exc
    except json.JSONDecodeError as exc:
        raise Failed(f"{path} did not return JSON: {exc}") from exc

    # ALS reports its own errors in the body with a 200.
    error = payload.get("Error") or payload.get("error")
    if error:
        raise Failed(f"{path}: {scrub(str(error), key)}")
    return payload


def fetch_profile(account: dict, key: str) -> dict:
    """GET /bridge. Query by UID once we know it — names can change."""
    params = {
        "platform": account["platform"],
        "version": 5,
        # Combine trackers of the same type before we read them, so a legend
        # carrying two kill trackers reports one number.
        "merge": 1,
    }
    if account.get("uid"):
        params["uid"] = account["uid"]
    else:
        params["player"] = account["gamertag"]
    return get("bridge", key, **params)


# ── merging ────────────────────────────────────────────────────────────────


def load_existing() -> dict:
    """Read the JSON back out of the generated JS so history accumulates."""
    if not OUT.exists():
        return {}
    text = OUT.read_text()
    match = re.search(r"window\.APEX_DATA\s*=\s*(\{.*\});?\s*$", text, re.S)
    if not match:
        raise Failed(f"{OUT.name} exists but has no window.APEX_DATA object in it")
    try:
        return json.loads(match.group(1))
    except json.JSONDecodeError as exc:
        raise Failed(f"{OUT.name} is not readable as JSON: {exc}") from exc


def number(value):
    """ALS sends numbers as numbers or strings depending on the tracker."""
    if isinstance(value, bool) or value is None:
        return None
    if isinstance(value, (int, float)):
        return value
    try:
        return int(str(value).replace(",", "").strip())
    except ValueError:
        return None


def merge_trackers(old: list, seen: list, today: str) -> list:
    """Keep the highest value ever recorded for each tracker.

    Every Apex tracker is a cumulative counter, so a smaller number means we
    caught a stale upstream cache, not that Ric un-killed anybody. A manual
    value stays manual until the API beats it.
    """
    merged = {t["key"]: dict(t) for t in old if t.get("key")}
    for tracker in seen:
        key = tracker.get("key")
        value = number(tracker.get("value"))
        if not key or value is None:
            continue
        existing = merged.get(key)
        if existing and number(existing.get("value")) is not None:
            if number(existing["value"]) >= value:
                continue
        merged[key] = {
            "key": key,
            "name": tracker.get("name") or key,
            "value": value,
            "source": "api",
            "asOf": today,
        }
    return sorted(merged.values(), key=lambda t: -(number(t.get("value")) or 0))


def tracked_kills(legends: dict) -> int:
    """Kills summed across every legend we have ever seen a kill tracker on.

    This is not career kills — it is career kills minus every legend Ric has
    never equipped a tracker on. The page says so.
    """
    total = 0
    for legend in legends.values():
        for tracker in legend.get("trackers", []):
            if tracker.get("key") == "kills":
                total += number(tracker.get("value")) or 0
    return total


def build(existing: dict, profile: dict, account: dict) -> dict:
    now = datetime.now(timezone.utc)
    today = date.today().isoformat()

    glob = profile.get("global") or {}
    realtime = profile.get("realtime") or {}
    rank = glob.get("rank") or {}
    legends_seen = (profile.get("legends") or {}).get("all") or {}

    legends = {name: dict(info) for name, info in (existing.get("legends") or {}).items()}

    for name, info in legends_seen.items():
        data = (info or {}).get("data") or []
        # ALS files the account-wide career trackers under a pseudo-legend
        # called "Global". Those are not a legend; they go to `career`.
        if name == "Global":
            continue
        if not data:
            continue
        entry = legends.get(name, {"trackers": []})
        entry["trackers"] = merge_trackers(entry.get("trackers", []), data, today)
        entry["lastSeen"] = today
        entry["equipped"] = bool(data)
        legends[name] = entry

    career = dict(existing.get("career") or {})
    # If Ric ever gets the Career Kills / Career Wins trackers, they arrive
    # under "Global" and beat the hand-typed numbers.
    for tracker in ((legends_seen.get("Global") or {}).get("data") or []):
        key = (tracker.get("key") or "").lower()
        value = number(tracker.get("value"))
        if value is None:
            continue
        for field, needles in (("kills", ("career_kills", "kills")),
                               ("wins", ("career_wins", "wins")),
                               ("games", ("games_played", "games"))):
            if key in needles and (number(career.get(field)) or 0) < value:
                career[field] = value
                career["source"] = "api"
                career["asOf"] = today

    data = {
        "generated": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source": "pull-apex.py",
        "live": True,
        "account": {
            "name": glob.get("name") or account["gamertag"],
            "uid": glob.get("uid") or account.get("uid"),
            "platform": glob.get("platform") or account["platform"],
            "level": number(glob.get("level")),
            "prestige": number(glob.get("levelPrestige")),
            "toNextLevelPercent": number(glob.get("toNextLevelPercent")),
        },
        "status": {
            "online": bool(number(realtime.get("isOnline"))),
            "inGame": bool(number(realtime.get("isInGame"))),
            "text": realtime.get("currentStateAsText"),
            "selectedLegend": realtime.get("selectedLegend"),
            "checked": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        },
        "rank": {
            "name": rank.get("rankName"),
            "div": number(rank.get("rankDiv")),
            "score": number(rank.get("rankScore")),
            "ladderPos": number(rank.get("ladderPosPlatform")),
        },
        "legends": legends,
        "career": career,
        "history": list(existing.get("history") or []),
    }

    # One point per day. A second run the same day updates that day in place.
    point = {
        "d": today,
        "trackedKills": tracked_kills(legends),
        "careerKills": number(career.get("kills")),
        "rp": data["rank"]["score"],
        "level": data["account"]["level"],
    }
    history = [p for p in data["history"] if p.get("d") != today]
    history.append(point)
    data["history"] = sorted(history, key=lambda p: p.get("d") or "")

    return data


def report(data: dict, existing: dict) -> None:
    account = data["account"]
    print(f"account   {account['name']} · {account['platform']} · level {account['level']}")
    rank = data["rank"]
    if rank["name"]:
        div = f" {rank['div']}" if rank["div"] else ""
        print(f"rank      {rank['name']}{div} · {rank['score']} RP")
    print(f"state     {data['status']['text'] or 'unknown'}")

    before = existing.get("legends") or {}
    print(f"legends   {len(data['legends'])} tracked ({len(data['legends']) - len(before):+d})")
    for name, info in sorted(
        data["legends"].items(),
        key=lambda kv: -(number((kv[1].get('trackers') or [{}])[0].get('value')) or 0),
    ):
        gained = ""
        old = before.get(name, {})
        old_kills = next((number(t.get("value")) for t in old.get("trackers", [])
                          if t.get("key") == "kills"), None)
        new_kills = next((number(t.get("value")) for t in info.get("trackers", [])
                          if t.get("key") == "kills"), None)
        if old_kills is not None and new_kills is not None and new_kills > old_kills:
            gained = f"  (+{new_kills - old_kills})"
        shown = ", ".join(
            f"{t['name']} {number(t.get('value')):,}" for t in info.get("trackers", [])
            if number(t.get("value")) is not None
        )
        print(f"          {name:<14} {shown}{gained}")

    career = data["career"]
    if career.get("kills"):
        print(f"career    {career['kills']:,} kills ({career.get('source')}, as of {career.get('asOf')})")
    else:
        print("career    not recorded — read the in-game career panel and fill in `career` by hand")
    print(f"history   {len(data['history'])} day(s)")

    untracked = [n for n, i in data["legends"].items() if not i.get("trackers")]
    if untracked:
        print(f"unequipped {', '.join(untracked)}")


def write(data: dict) -> None:
    OUT.write_text(HEADER + json.dumps(data, indent=1) + ";\n")


def main() -> int:
    try:
        account = read_account()
        key = api_key(account["gamertag"])
    except Misconfigured as exc:
        print(f"apex: {exc}", file=sys.stderr)
        return 2

    try:
        existing = load_existing()
        profile = fetch_profile(account, key)
        data = build(existing, profile, account)
        write(data)
    except Failed as exc:
        print(f"apex: {scrub(str(exc), key)}", file=sys.stderr)
        return 1

    report(data, existing)

    # Remember the UID so later runs skip the name lookup.
    if data["account"]["uid"] and not account.get("uid"):
        account["uid"] = data["account"]["uid"]
        ACCOUNT.write_text(json.dumps(account, indent=2) + "\n")
        print(f"cached uid {account['uid']} in {ACCOUNT.name}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
