#!/bin/bash
# Weekly board sync, run by launchd (see board-sync.plist).
#
# Pulls both logbooks and regenerates board-data.js. It will commit that file on
# its own, but only when it is the single thing that changed and the repo is on
# main — anything else and it leaves the working tree exactly as it found it and
# says so in the log. It never pushes: on this repo a push is a publish, and
# that stays Ric's call.
#
# Log: ~/Library/Logs/board-sync.log

set -uo pipefail

REPO="/Users/ricmassey/RicsWebsite"
DATA="projects/climbing/board-data.js"
LOG="$HOME/Library/Logs/board-sync.log"
PYTHON="$REPO/projects/climbing/.board-venv/bin/python"

mkdir -p "$(dirname "$LOG")"
exec >>"$LOG" 2>&1
echo ""
echo "───────────── $(date '+%Y-%m-%d %H:%M:%S') ─────────────"

cd "$REPO" || { echo "no repo at $REPO"; exit 1; }
[ -x "$PYTHON" ] || { echo "no venv python — run: python3 -m venv projects/climbing/.board-venv"; exit 1; }

before=$(git rev-parse --quiet --verify HEAD)
"$PYTHON" projects/climbing/pull-boards.py
status=$?

# A failed sync is usually Aurora having moved and boardlib not having caught up
# yet. Try exactly one upgrade-and-retry before giving up, so a routine breakage
# fixes itself overnight instead of waiting for someone to notice.
#
# Exit 2 means a missing username or Keychain password. No upgrade fixes that,
# so don't waste the round trip — just say what's missing.
if [ $status -eq 2 ]; then
  echo "not a boardlib problem — the credentials above need sorting out"
elif [ $status -ne 0 ]; then
  echo "sync failed (exit $status) — checking whether boardlib is stale"
  projects/climbing/board-upgrade.sh --install
  upgrade=$?
  if [ $upgrade -eq 11 ]; then
    # Ric said no, or wasn't at the Mac to be asked. Nothing changed, so a
    # retry would fail identically — leave it for the next run.
    echo "no upgrade taken — not retrying"
  elif [ $upgrade -ne 0 ]; then
    echo "couldn't check for an upgrade — not retrying"
  else
    echo "retrying the sync once"
    "$PYTHON" projects/climbing/pull-boards.py
    status=$?
  fi
fi

if [ $status -ne 0 ]; then
  echo "sync still failing (exit $status) — leaving everything alone"
  exit $status
fi

if git diff --quiet -- "$DATA"; then
  echo "no new board entries"
  exit 0
fi

branch=$(git rev-parse --abbrev-ref HEAD)
dirty=$(git status --porcelain | grep -v " $DATA\$" | grep -v "^?? " || true)

if [ "$branch" != "main" ]; then
  echo "new board data, but on branch '$branch' — left uncommitted for Ric"
  exit 0
fi
if [ -n "$dirty" ]; then
  echo "new board data, but other files are modified — left uncommitted:"
  echo "$dirty"
  exit 0
fi

git add "$DATA"
git commit -q -m "Climbing: this week's board sessions

Generated by pull-boards.py on the weekly timer. Not pushed — publishing
is still a deliberate act." && echo "committed $(git rev-parse --short HEAD) (not pushed)"

echo "run 'git push' when you want it live"
[ "$before" = "$(git rev-parse HEAD)" ] && echo "nothing committed"
exit 0
