// Generated by build-data.py — the newest day out, for the sitewide banner.
window.RELAY_LATEST_CLIMB = {
 "date": "2026-07-27",
 "kind": "new routes sent",
 "title": "Maranda Rayne, Amarillo sunset, Cavers Route — Red River Gorge",
 "description": "3 sent · with Dorcey, Silas, Chayten",
 "href": "projects/climbing/index.html#trip-2026-07-27"
};
